::: {.content-hidden}
$
{{< include macros.tex >}}
$
:::


# Revision Guide

## Recommended revision strategy

1. Make sure you are very comfortable with the Definitions, Statements, Proofs, and Examples contained in this Revision Guide.

2. Make sure you are comfortable with the Tutorial and Homework questions.

3. Make sure you are comfortable with the 2023/24 Exam Paper questions.

4. Make sure you are comfortable with the Checklist in @sec-checklist.


## Checklist {#sec-checklist}

Overall, you should be comfortable with the following topics/taks:


**Preliminaries**

- Prove that $\sqrt{p} \notin \Q$ for $p$ a prime number.
- 

**Complex Numbers**

- Sum, multiplication and division of complex numbers
- Computing the complex conjugate
- Computing the inverse of a complex number
- Find modulus and argument of a complex number
- Compute Cartesian, Trigonometric and Exponential form of a complex number
- Complex exponential and its properties
- Computing powers of complex numbers
- Solving degree 2 polynomial equations in $\C$
- Long division of polynomials
- Solving higher degree polynomial equations in $\C$
- Finding the roots of unity
- Finding the n-th roots of a complex number




## Preliminaries


::: Theorem
The number $\sqrt{2}$ does not belong to $\Q$.
:::


::: Proof

Aassume by contradiction that 
$$
\sqrt{2} \in \Q \,.
$$ {#eq-contradiction-root-2-false}

1. Therefore, there exists $q \in \Q$ such that 
$$
q = \sqrt{2} \, .
$$ {#eq-contradiction-root-2}
2. Since $q \in \Q$, by definition we have
$$
q = \frac{m}{n}
$$
for some $m,n \in \N$ with $n \neq 0$.
3. Recalling (@eq-contradiction-root-2), we then have
$$
\frac{m}{n} = \sqrt{2} \,.
$$
4. We can square the above equation to get
$$
 \frac{m^2}{n^2} = 2 \,.
$$ {#eq-contradiction-root-2-2}
5. **Withouth loss of generality**, we can **assume** that $m$ and $n$ have no common factors.
    
    
6.  Equation (@eq-contradiction-root-2-2) implies 
$$
m^2 = 2 n^2 \,.
$$ {#eq-contradiction-root-2-3}
Therefore the integer $m^2$ is an even number. 

   

7. Since $m^2$ is an even number, it follows that also $m$ is an even number. Then there exists $p \in \N$ such that 
$$
m = 2p \,.
$$ {#eq-contradiction-root-2-4}

   

8. If we substitute (@eq-contradiction-root-2-4) in (@eq-contradiction-root-2-3) we get
$$
m^2 = 2n^2 \, \implies \,  (2p)^2 = 2n^2 \, \implies \,  4 p^2 = 2 n^2
$$
Dividing both terms by $2$, we obtain
$$
n^2 = 2p^2\,. 
$${#eq-contradiction-root-2-5}
9. We now make a series of observations:
    * Equation (@eq-contradiction-root-2-5) says that $n^2$ is even.
    * The same argument in Step 7 guarantees that also $n$ is even.
    * We have already seen that $m$ is even.
    * Therefore $n$ and $m$ are both even.  
    * Hence $n$ and $m$ have $2$ as common factor.
    * But Step 5 says that $n$ and $m$ have no common factors.
    * **Contradiction**
10. Our reasoning has run into a **contradiction**, stemming  from assumption (@eq-contradiction-root-2-false). Therefore (@eq-contradiction-root-2-false) is **FALSE**, and so 
$$
\sqrt{2} \notin \Q \,
$$
ending the proof.
:::


### Set Theory


::: Definition
For two sets $A$ and $B$ we define their **union** as the set
$$
A \cup B := \{ x\, \colon \, x \in A  \, \text{ or } \, x \in B \} \,.
$$
The **intersection** of $A$ and $B$ is defined by
$$
A \cap B := \{ x\, \colon \, x \in A  \, \text{ and } \, x \in B \} \,.
$$
We denote the **empty set** by the symbol $\emptyset$. Two sets are **disjoint** if 
$$
A \cap B = \emptyset \,.
$$
Given two sets $A$ and $B$, we say that $A$ is **contained** in $B$, in symbols
$$
A \subseteq B  \,,
$$
if all the elements of $A$ are also contained in $B$. Two sets $A$ and $B$ are **equal**, in symbols
$$
A=B \,,
$$
if they contain the same elements. 
:::


::: Proposition

Let $A$ and $B$ be sets. Then 
$$
A=B \quad \iff \quad A \subseteq B \,\, \text{ and } \,\, B \subseteq A \,.
$$

:::



::: Definition

Let $\Omega$ be a set, and $A_n \subseteq \Omega$ a family of subsets, where $n \in \N$. 

1. The **infinte union** of the $A_n$ is the set
$$
\bigcup_{n \in \N} A_n := \{ x \in \Omega \, \colon \, x \in A_n \,\, \text{ for at least one } \,\, n \in \N \} \,.
$$

2. The **infinte intersection** of the $A_n$ is the set 
$$
\bigcap_{n \in \N} A_n := \{ x \in \Omega \, \colon \, x \in A_n \,\, \text{ for all } \,\, n \in \N \} \,.
$$

:::


::: Example 

**Question.**
Define $\Omega:=\N$ and a family $A_n$ by
$$
A_n = \{ n, n+1, n+2, n+3,  \ldots \} \,, \quad n \in \N \,.
$$

1. Prove that
$$
\bigcup_{n \in \N} A_n = \N \,.
$$ {#eq-infinite-union}

2. Prove that 
$$
\bigcap_{n \in \N} A_n = \emptyset \,.
$$ {#eq-infinite-intersection}

**Solution.**

1. Assume that $m \in \cup_n A_n$. Then $m \in A_n$ for at least one $n \in \N$. Since $A_n \subseteq \N$, we conclude that $m \in \N$. This shows 
$$
\bigcup_{n \in \N} A_n \subseteq \N \,.
$$
Conversely, suppose that $m \in \N$. By definition $m \in A_m$. Hence there exists at least one index $n$, $n=m$ in this case, such that $m \in A_n$. Then by definition $m \in \cup_{n \in \N} A_n$, showing that
$$
\N \subseteq \bigcup_{n \in \N} A_n \,.
$$
This proves (@eq-infinite-union).

2. Suppose that (@eq-infinite-intersection) is false, i.e., 
$$
\bigcap_{n \in \N} A_n \neq \emptyset \,.
$$
This means there exists some $m \in \N$ such that $m \in \cap_{n \in \N} A_n$. Hence, by definition, $m \in A_n$ for all $n \in \N$. However $m \notin A_{m+1}$, yielding a contradiction. Thus (@eq-infinite-intersection) holds.
:::



::: Definition
Let $A,B \subseteq \Omega$. The **complement** of $A$ with respect to $B$ is the set of elements of $B$ which do not belong to $A$, that is
$$
B \smallsetminus A := \{ x \in \Omega \, \colon \, x \in B \, \text{ and } \, x \notin A \} \,.
$$
In particular, the complement of $A$ with respect to $\Omega$ is denoted by 
$$
A^c := \Omega \smallsetminus A := \{ x \in \Omega \, \colon \, x \notin A \} \,.
$$
:::


::: Example

**Question.** Suppose $A, B \subseteq \Omega$. Prove that
$$
A \subseteq B  \iff B^c \subseteq A^c \,.
$$

**Solution.** Let us prove the above claim:

- First implication $\implies$:  
Suppose that $A \subseteq B$. We need to show that $B^c \subseteq A^c$. Hence, assume $x \in B^c$. By definition this means that $x \notin B$. Now notice that we cannot have that $x \in A$. Indeed, assume $x \in A$.  By assumption we have $A \subseteq B$, hence $x \in B$. But we had assumed $x \in B$, contradiction. Therefore it must be that $x \notin A$. Thus $B^c \subseteq A^c$.

- Second implication $\impliedby$:  Note that, for any set, 
$$
(A^c)^c = A \,.
$$
Hence, by the first implication,
$$
B^c \subseteq A^c \, \implies \, (A^c)^c \subseteq (B^c)^c \, \implies \, A \subseteq B \,.
$$
:::



::: Proposition
## De Morgan's Laws

Suppose $A,B \subseteq \Omega$. Then
$$
(A \cap B)^c = A^c \cup B^c  \,, \qquad 
(A \cup B)^c = A^c \cap B^c  \,.
$$ 

:::



::: Definition
Let $\Omega$ be a set. The **power set** of $\Omega$ is
$$
\mathcal{P}(\Omega) := \{ A \divider A \subseteq \Omega \}\,.
$$
:::

::: Example

**Question.** Compute the power set of
$$
\Omega = \{ x, y, z \}\,.
$$

**Solution.** $\mathcal{P}(\Omega)$ has $2^3 = 8$, and
\begin{align}
\mathcal{P}(\Omega) = \{ \emptyset, & \, \{x\} , \,  \{y\} , \, \{z\} , \{x,y\} \\
&  \{x,z\}, \, \{y,z\} , \, \{x,y,z\} \} \,. 
\end{align}
:::



::: Definition

Let $A,B$ be sets. The **product** of $A$ and $B$ is the set of pairs
$$
A \times B := \{ (a,b) \, \colon \, a \in A, \, b \in B \} \,.
$$

:::



### Relations

::: Definition

Suppose $A$ is a set. A **binary relation** $R$ on $A$ is a subset 
$$
R \subseteq A \times A \,.
$$

:::

::: Definition
### Equivalence relation

A binary relation $R$ is called an **equivalence relation** if it satisfies the following properties:

1. **Reflexive**: For each $x \in A$ one has 
$$
(x,x) \in R \,, 
$$

2. **Symmetric**: We have
$$
(x,y) \in R \implies (y,x) \in R
$$


3. **Transitive**: We have
$$
(x,y) \in R \,, \,\, (y,z) \in R  \implies (x,z) \in R 
$$


If $(x,y) \in R$ we write
$$
x \sim y 
$$
and we say that $x$ and $y$ are **equivalent**.

:::



::: Definition
### Equivalence classes

Suppose $R$ is an **equivalence relation** on $A$. The **equivalence class** of an element $x \in A$ is the set
$$
[x]:=\{ y \in A \, \colon \, y \sim x \} \,.
$$
The set of equivalence classes of elements of $A$ with respect to the equivalence relation $R$ is denoted by 
$$
A / R \, := A / \!\sim \, :=  \,\{ [x] \, \colon \, x \in A \} \,.
$$


:::




::: Proposition

Let $\sim$ be an equivalence relation on $A$. Then

1. For each $x \in A$ we have
$$
[x] \neq \emptyset
$$

2. For all $x,y \in A$ it holds
$$
x \sim y \quad \iff \quad  [x] = [y] \,.
$$

:::




::: Example
### Equality is an equivalence relation

**Question.** The equality defines a **binary relation** on $\Q \times \Q$, via
$$
R:=\{ (x,y) \in \Q \times \Q \, \colon \, x=y  \} \,.
$$

1. Prove that $R$ is an **equivalence relation**.
2. Prove that $[x] = \{x\}$ and compute $\Q / R$.

**Solution.** 

1. We need to check that $R$ satisfies the 3 properties of an equivalence relation:

    - Reflexive: It holds, since $x=x$ for all $x \in \Q$,

    - Symmetric: Again $x = y$ if and only if $y = x$,

    - Transitive: If $x = y$ and $y = z$ then $x = z$.

    Therefore, $R$ is an equivalence relation.

2. The class of equivalence of $x \in \Q$ is given by
$$
[x] = \{ x \}\,,
$$
that is, this relation is quite trivial, given that each element of $\Q$ can only be related to itself. The quotient space is then 
$$
\Q / R = \{ [x] \divider x \in \Q \} = \{  \{ x\} \divider x \in \Q \}  \,.
$$

:::



::: Example

**Question.** Let $R$ be the binary relation on the set $\Q$ of rational numbers defined by
$$
x \sim y  \iff x-y \in \Z \,.
$$

1. Prove that $R$ is an equivalence relation on $\Q$.
2. Compute $[x]$ for each $x \in \Q$.
3. Compute $\Q/R$.


**Solution.**

1. We have:

    - Reflexive: Let $x \in \Q$. Then $x-x = 0$ and $0 \in \Z$. Thus $x \sim x$.

    - Symmetric: If $x \sim y$ then $x-y \in \Z$. But then also  
    $$
    -(x-y) = y - x \in \Z
    $$
    and so $y \sim x$.

    - Transitive: Suppose $x \sim y$ and $y \sim z$. Then 
    $$
    x - y \in \Z \,  \text{ and } \, y - z \in \Z \,.
    $$
    Thus, we have
    $$
    x-z = (x-y) + (y-z) \in \Z
    $$
    showing that $x \sim z$. 

    Thus, we have shown that $R$ is an equivalence relation on $\Q$.

2. Note that
$$
y -x \in \Z 
$$
is equivalent to
$$
\exists \, n \in \Z \, \text{ s.t. } \, y - x = n
$$
which again is equivalent to 
$$
\exists \, n \in \Z \, \text{ s.t. } \, y = x + n \,.
$$
In summary we have
$$
x \sim y \quad \iff \quad \exists \, n \in \Z \, \text{ s.t. } \, y = x + n \,.
$$
Therefore the equivalence classes with respect to $\sim$ are
$$
 [x] = \{  x + n \ \colon \ n \in \Z  \}  \,.
$$
Each equivalence class has exactly one element in $[0,1) \cap \Q$, meaning that:
$$
\forall x \in \Q \,, \,\, \exists! \, q \in \Q \st  0 \leq q < 1 \, \text{ and } \, q \in [x]\,.
$${#eq-equivalence-rel}
Indeed: take $x \in \Q$ arbitrary. Then $x \in [n,n+1)$ for some 
$n \in \Z$. Setting $q:=x-n$ we obtain that
$$
x = q + n \,, \qquad q \in [0,1) \,,
$$
proving (@eq-equivalence-rel). In particular (@eq-equivalence-rel) implies that for each $x \in \Q$ there exists $q \in [0,1) \cap \Q$ such that
$$
[x] = [q] \,.
$$

3. From Point 2 we conclude that
$$
\Q / R = \{ [x] \divider x \in \Q \} = \{ q \in \Q \divider 0 \leq q <1  \} \,.
$$
:::




::: Definition
### Partial order

A binary relation $R$ on $A$ is called a **partial order** if it satisfies the following properties:

1. **Reflexive**: For each $x \in A$ one has 
$$
(x,x) \in R \,, 
$$

2. **Antisymmetric**: We have
$$
(x,y) \in R \,  \text{ and } \, (y,x) \in R \implies x = y 
$$


3. **Transitive**: We have
$$
(x,y) \in R \,, \,\, (y,z) \in R  \implies (x,z) \in R 
$$
:::




:::  Definition
### Total order

A binary relation $R$ on $A$ is called a **total order relation** if it satisfies the following properties:

1. **Partial order**: $R$ is a partial order on $A$.
2. **Total**: For each $x,y \in A$ we have
$$
(x, y) \in R \,\, \mbox{ or } \,\, (y,x) \in R \,.
$$

:::




::: Example
### Set inclusion is a partial order but not total order

**Question.** Let $\Omega$ be a non-empty set and consider its **power set**
$$
\mathcal{P}(\Omega) = \{ A \divider A \subseteq \Omega  \}\,.
$$
The inclusion defines **binary relation** on $\mathcal{P}(\Omega) \times \mathcal{P}(\Omega)$, via
$$
R:=\{ (A,B) \in \mathcal{P}(\Omega) \times \mathcal{P}(\Omega) \, \colon \, A \subseteq B  \} \,.
$$

1. Prove that $R$ is an **order relation**.
2. Prove that $R$ is **not a total order**.

**Solution.**

1. Check that $R$ is a partial order relation on $\mathcal{P}(\Omega)$:
    - Reflexive: It holds, since $A \subseteq A$ for all $A \in \mathcal{P}(\Omega)$.
    - Antisymmetric: If $A \subseteq B$ and $B \subseteq A$, then $A=B$.
    - Transitive: If $A \subseteq B$ and $B \subseteq C$, then, by definition of inclusion, $A \subseteq C$.

2. In general, $R$ is **not** a total order. For example consider
$$
\Omega = \{x, y\}\,.
$$
Thus
$$
\mathcal{P}(\Omega)  = \{ \emptyset , \, \{x\} , \, \{y\} , \, \{x,y\} \}\,.
$$
If we pick $A=\{x\}$ and $B=\{y\}$ then $A \cap B = \emptyset$, meaning that 
$$
A \not\subseteq B \,, \quad  B \not\subseteq A \,.
$$
This shows $R$ is not a total order.
:::




::: Example
### Inequality is a total order

**Question.** Consider the binary relation
$$
R:=\{ (x,y) \in \Q \times \Q \, \colon \, x \leq y  \} \,.
$$
Prove that $R$ is a **total order relation**.

**Solution.** We need to check that:

1. Reflexive: It holds, since $x \leq x$ for all $x \in \Q$,

2. Antisymmetric: If $x \leq y$ and $y \leq x$  then $x = y$.

3. Transitive: If $x \leq y$ and $y \leq z$ then $x \leq z$.

Finally, we halso have that $R$ is a **total order** on $\Q$, since for all $x,y \in \Q$ we have
$$
x \leq y \,\, \text{ or } \,\, y \leq x \,.
$$
:::




### Absolute value

::: Definition
### Absolute value 
For $x \in \R$ we define its **absolute value** as the quantity
$$
|x| = 
\begin{cases}
x  & \text{ if } \, x \geq 0 \\
-x  & \text{ if } \, x < 0 
\end{cases}
$$
:::

::: Proposition
For all $x \in \R$ they hold:

1. $|x| \geq 0$.
2. $|x| = 0$ if and only if $x = 0$.
3. $|x| = |-x|$.

:::


::: {.Lemma #lemma-absolute-value}
Let $x,y \in \R$. Then
$$
|x| \leq y  \iff -y \leq x \leq y \,.
$$
:::

::: Corollary
Let $x,y \in \R$. Then
$$
|x| < y  \iff -y < x < y \,.
$$
:::




::: Theorem
### Triangle inequality  {#theorem-triangle-inequality}

For every $x, y \in \R$ we have
$$
| |x| - |y| | \leq |x+y| \leq |x| + |y| \,.
$$ {#eq-triangle-inequality}
:::




::: Proposition
For any $x,y \in \R$ it holds
$$
||x|-|y|| \leq |x-y| \leq |x|+|y|\,.
$${#eq-triangle-inequality-bis}
Moreover for any  $x,y,z \in \R$ it holds
$$
|x-y| \leq |x-z| + |z-y| \,.
$$
:::



### Induction



::: Definition
### Principle of Inducion

Let $\alpha(n)$ be a statement which depends on $n \in \N$. Suppose that 

1. $\alpha(1)$ is true, and
2. Whenever $\alpha(n)$ is true, then $\alpha(n+1)$ is true.

Then $\alpha(n)$ is true for all $n \in \N$.
:::


::: Example 
### Formula for summing first $n$ natural numbers

**Question.** Prove by induction that the following formula holds for all $n \in \N$:
$$
1 + 2 + 3 + \ldots + (n-1) + n = \frac{n(n+1)}{2} \,.
$$ {#eq-formula-sum-naturals}


**Solution**. Define
$$
S(n) = 1 + 2 + \ldots + n \,.
$$
This way the formula at (@eq-formula-sum-naturals) is equivalent to
$$
S(n) = \frac{n(n+1)}{2} \,, \quad \forall \, n \in \N \,.
$$

1. It is immediate to check that (@eq-formula-sum-naturals) holds for $n=1$.
2. Suppose (@eq-formula-sum-naturals) holds for $n = k$. Then
\begin{align}
S(k+1) & = 1 + \ldots +  k + (k+1) \\
       & = S(k) + (k+1) \\
       & = \frac{k(k+1)}{2}  + (k+1) \\
& = \frac{ k(k+1) + 2(k+1) }{2} \\
& = \frac{(k+1)(k+2)}{2}
\end{align}
where in the first equality we used that (@eq-formula-sum-naturals) holds for $n=k$. We have proven that
$$
S(k+1) = \frac{(k+1)(k+2)}{2}\,.
$$
The RHS in the above expression is exactly the RHS of  (@eq-formula-sum-naturals) computed at $n = k+1$. Therefore, we have shown that formula (@eq-formula-sum-naturals) holds for $n = k+1$.

By the Principle of Induction, we conclude that (@eq-formula-sum-naturals) holds for all $n \in \N$.

:::


::: Example
### Bernoulli's inequality

**Question.** Let $x \in \R$ with $x>-1$. Bernoulli's inequality states that
$$
(1+x)^{n} \geq 1+n x \,, \quad \forall \, n \in \N \,.
$${#eq-bernoulli-inequality}
Prove Bernoulli's inequality by induction.


**Solution.** Let $x \in \mathbb{R}, x>-1$. We prove the statement by induction:

- Base case: (@eq-bernoulli-inequality) holds with equality when $n=1$.

- Induction hypothesis: Let $k \in \N$ and suppose that (@eq-bernoulli-inequality) holds for $n=k$, i.e.,
$$
(1+x)^{k} \geq 1+k x \,.
$$
Then
\begin{align*}
(1+x)^{k+1} & = (1+x)^{k}(1+x) \\
            & \geq(1+k x)(1+x) \\
            & =1+k x+x+k x^{2} \\
            & \geq 1+(k+1) x \,,
\end{align*}
where we used that $kx^2 \geq 0$. Then (@eq-bernoulli-inequality) holds for $n=k+1$.

By induction we conclude (@eq-bernoulli-inequality).

:::


## Real Numbers


### Fields


::: Definition
### Binary operation
A binary operation on a set $K$ is a function 
$$
\circ \ \colon K \times K \to K
$$
which maps the ordered pair $(x,y)$ into $x \circ y$.
:::



::: Definition
Let $K$ be a set and $\circ \ \colon K \times K \to K$ be a binary operation on $K$. We say that:

1. $\circ$ is **commutative** if 
    $$
    x \circ y = y \circ x \,, \quad \, \forall \, x,y \in K
    $$
2. $\circ$ is **associative** if 
    $$
    (x \circ y) \circ z = x \circ (y \circ z) \,, \quad \, \forall \, x,y,z \in K
    $$
3. An element $e \in K$ is called **neutral element** of $\circ$ if
    $$ 
    x \circ e = e \circ x = x \,, \quad \, \forall \, x \in K
    $$
4. Let $e$ be a neutral element of $\circ$ and let $x \in K$. An element $y \in K$ is called an **inverse** of $x$ with respect to $\circ$ if 
$$
x \circ y = y \circ x = e \,.
$$
:::




::: Example

**Question.** Let $K=\{0,1\}$ be a set with binary operation $\circ$ defined by the table
$$
\begin{array}{c|cc}
 \circ & 0 & 1 \\ \hline
 0     & 1 & 1 \\
 1     & 0 & 0 \\
\end{array}	
$$

1. Is $\circ$ commutative? Justify your answer.

2. Is $\circ$ associative? Justify your answer.

**Solution.**

1. We have
$$
0 \circ 1 = 1 \, , \quad 1 \circ 0 = 0
$$
and therefore
$$
0 \circ 1 \neq 1 \circ 0 \,.
$$
showing that $\circ$ is not commutative.

2. We have
$$
(0 \circ 1) \circ 1 = 1 \circ 1 = 0 \,,
$$
while 
$$
0 \circ (1 \circ 1) = 0 \circ 0 = 1 \,,
$$
so that 
$$
(0 \circ 1) \circ 1  \neq 0 \circ (1 \circ 1)\,.
$$
Thus, $\circ$ is not associative.

:::




::: Definition
### Field

Let $K$ be a set with binary operations of **addition** 
$$
+\ \colon K \times K \to K \,, \quad (x,y) \mapsto x + y 
$$
and **multiplication** 
$$
\cdot\ \colon K \times K \to K \,, \quad (x,y) \mapsto x \cdot y  = xy \,. 
$$ 
We call the triple $(K, + , \cdot)$ a **field** if:

1. The addition $+$ satisfies: $\,\forall \, x,y,z \in K$
    - (A1) **Commutativity and Associativity**: 
    $$
    x+y = y+x 
    $$
    $$
    (x+y)+z = x+(y+z) 
    $$
    - (A2) **Additive Identity**: There exists a **neutral element** in $K$ for $+$, which we call $0$. It holds:
    $$ 
    x + 0 = 0 + x = x 
    $$
    - (A3) **Additive Inverse**: There exists an **inverse** of $x$ with respect to $+$. We call this element the **additive inverse** of $x$ and denote it by $-x$. It holds
    $$
    x + (-x) = (-x) + x = 0 
    $$

2. The multiplication $\cdot$ satisifes: $\,\forall \, x,y,z \in K$
    - (M1) **Commutativity and Associativity**: 
    $$
    x \cdot y = y \cdot x 
    $$
    $$
    (x \cdot y) \cdot z = x \cdot (y \cdot z) 
    $$
    - (M2) **Multiplicative Identity**: There exists a **neutral element** in $K$ for $\cdot$, which we call $1$. It holds:
    $$ 
    x \cdot 1 = 1 \cdot x = x 
    $$
    - (M3) **Multiplicative Inverse**: If $x \neq 0$ there exists an **inverse** of $x$ with respect to $\cdot$. We call this element the **multiplicative inverse** of $x$ and denote it by $x^{-1}$. It holds
    $$
    x \cdot x^{-1} = x^{-1} \cdot x = 1 
    $$

3. The operations $+$ and $\cdot$ are related by 
    - (AM) **Distributive Property**: $\,\forall \, x,y,z \in K$
    $$
    x \cdot (y + z) = (x \cdot y) + (y \cdot z) \,.
    $$
:::


::: Theorem
Consider the sets $\N$, $\Z$, $\Q$ with the usual operations $+$ and $\cdot$. We have:

- $(\N, + , \cdot)$ is **not a field**.

- $(\Z, + , \cdot)$ is **not a field**.

- $(\Q, + , \cdot)$ **is a field**.


:::






::: Theorem

Let $K$ with $+$ and $\cdot$ defined by
$$
\begin{array}{c|cc}
 + & 0 & 1 \\ \hline
 0 & 0 & 1 \\
 1 & 1 & 0 \\
\end{array}	
\qquad \qquad
\begin{array}{c|cc}
\cdot & 0 & 1 \\ \hline
    0 & 0 & 0 \\
    1 & 0 & 1 \\
\end{array}
$$
Then $(K,+,\cdot)$ is a field. 

:::




::: Proposition
### Uniqueness of neutral elements and inverses

Let $(K,+,\cdot)$ be a field. Then

1. There is a unique element in $K$ with the property of $0$.
2. There is a unique element in $K$ with the property of $1$.
3. For all $x \in K$ there is a unique additive inverse $-x$.
4. For all $x \in K$, $x \neq 0$, there is a unique multiplicative inverse $x^{-1}$.
:::

::: Proof
1. Suppose that $0 \in K$ and $\widetilde{0} \in K$ are both neutral element of $+$, that is, they both satisfy (A2). Then 
$$
0 + \widetilde{0} = 0
$$
since $\widetilde{0}$ is a neutral element for $+$. Moreover
$$
\widetilde{0} + 0 = \widetilde{0}
$$
since $0$ is a neutral element for $+$. By commutativity of $+$, see property (A1), we have
$$
0 = 0 + \widetilde{0} = \widetilde{0} + 0 = \widetilde{0} \,,
$$
showing that $0 = \widetilde{0}$. Hence the neutral element for $+$ is unique.
2. Exercise.
3. Let $x \in K$ and suppose that $y, \widetilde{y} \in K$ are both additive inverses of $x$, that is, they both satisfy (A3). Therefore
$$
x + y = 0
$$
since $y$ is an additive inverse of $x$ and
$$
x + \widetilde{y} = 0 
$$
since $\widetilde{y}$ is an additive inverse of $x$. Therefore we can use commutativity and associativity and of $+$, see property (A1), and the fact that $0$ is the neutral element of $+$, to infer
\begin{align*}
y & = y + 0 = y + (x + \widetilde{y}) \\ 
  & = (y + x) + \widetilde{y} = (x + y) + \widetilde{y} \\
  & = 0 + \widetilde{y} = \widetilde{y} \,,    
\end{align*}
concluding that $y = \widetilde{y}$. Thus there is a unique additive inverse of $x$, and 
$$
y = \widetilde{y} = -x \,,
$$
with $-x$ the element from property (A3).
4. Exercise.
:::



::: Definition
Let $K$ be a set with binary operations $+$ and $\cdot$, and with an order relation $\leq$. We call $(K,+,\cdot,\leq)$ an **ordered field** if:

1. $(K,+,\cdot)$ is a field

3. There $\leq$ is of **total order** on $K$:  $\, \forall \, x, y, z \in K$ 
    - (O1) **Reflexivity**: 
    $$
    x \leq x
    $$ 
    - (O2) **Antisymmetry**: 
    $$
    x \leq y \, \mbox{ and } \, y \leq x \,\, \implies \,\, x = y 
    $$
    - (O3) **Transitivity**: 
    $$
    x \leq y \,\, \mbox{ and } \,\, y \leq z \,\, \implies \,\, x = z 
    $$
    - (O4) **Total order**:  
    $$
    x \leq y \,\, \mbox{ or } \,\, y \leq x 
    $$

4. The operations $+$ and $\cdot$, and the total order $\leq$, are related by the following properties: $\, \forall x, y, z \in K$
    - (AM) **Distributive**: Relates addition and multiplication via
    $$
    x \cdot (y + z) = x \cdot y + x \cdot z 
    $$
    - (AO) Relates addition and order with the requirement:
    $$
    x \leq y \,\, \implies \,\, x + z \leq y + z
    $$
    - (MO) Relates multiplication and order with the requirement:
    $$
    x \geq 0, \, y \geq 0  \,\, \implies \,\, x \cdot y  \geq 0
    $$
:::


::: Theorem
$(\Q,+,\cdot,\leq)$ is an **ordered field**.
:::





 
### Supremum and infimum


::: Definition
### Upper bound, bounded above, supremum, maximum

Let $A \subseteq K$:

1. We say that $b \in K$ is an **upper bound** for $A$ if
$$
a \leq b \,, \quad \forall \, a \in A \,.
$$
2. We say that $A$ is **bounded above** if there exists and upper bound $b \in K$ for $A$.

3. We say that $s \in K$ is the **least upper bound** or **supremum** of $A$ if:
    - $s$ is an upper bound for $A$,
    - $s$ is the smallest upper bound of $A$, that is, 
    $$
    \mbox{If } \, b \in K \, \mbox{ is upper bound for } \, A \, \mbox{ then } \, s \leq b \,.  
    $$
    If it exists, the supremum is denoted by
    $$
    s = \sup \ A \,.
    $$

4. Let $A \subseteq K$. We say that $M \in K$ is the **maximum** of $A$ if:
$$
M \in A   \,\, \mbox{ and } \,\, a \leq M  \,, \, \forall a \in A \,.
$$
If it exists, we denote the maximum by
$$
M = \max A \,.
$$

:::



::: Remark
Note that if a set $A \subseteq K$ in **NOT** bounded above, then the supremum does not exist, as there are no upper bounds of $A$. 
:::






::: Proposition 
### Relationship between Max and Sup {#proposition-max-sup}

Let $A \subseteq K$. If the maximum of $A$ exists, then also the supremum exists, and
$$
\sup A = \max A \,.
$$
:::

::: Definition
### Upper bound, bounded below, infimum, minimum

Let $A \subseteq K$:

1. We say that $l \in K$ is a **lower bound** for $A$ if
$$
l \leq a \,, \quad \forall \, a \in A \,.
$$
2. We say that $A$ is **bounded below** if there exists a lower bound $l \in K$ for $A$.
3. We say that $i \in K$ is the **greatest lower bound** or **infimum** of $A$ if:

    - $i$ is a lower bound for $A$,
    - $i$ is the largest lower bound of $A$, that is, 
    $$
    \mbox{If } \, l \in K \, \mbox{ is a lower bound for } \, A \, \mbox{ then } \, l \leq i \,.  
    $$
If it exists, the infimum is denoted by 
$$
i = \inf A \,.
$$
4. We say that $m \in K$ is the **minimum** of $A$ if:
$$
m \in A   \,\, \mbox{ and } \,\, m \leq a  \,, \, \forall a \in A \,.
$$
If it exists, we denote the minimum by
$$
m = \min A \,.
$$
:::



::: Proposition
Let $A \subseteq K$. If the minimum of $A$ exists, then also the infimum exists, and
$$
\inf A = \min A \,.
$$  

:::


::: Proposition
Let $A \subseteq K$. If $\inf A$ and $\sup A$ exist, then
$$
\inf A \leq a \leq \sup A \,, \quad \forall \, a \in A \,.
$$
:::


::: Proposition
### Relationship between sup and inf {#proposition-inf-sup}

Let $A \subseteq K$. Define 
$$
- A := \{ - a \divider a \in A \} \,.
$$
They hold

1. If $\sup A$ exists, then $\inf A$ exists and
$$
\inf(-A) = - \sup A \,.
$$
2. If $\inf A$ exists, then $\sup A$ exists and
$$
\sup(-A) = - \inf A \,.
$$
:::





### Axioms of Real Numbers


::: Definition
### Completeness

Let $(K,+,\cdot,\leq)$ be an ordered field. We say that $K$ is **complete** if it holds the property:

- (AC) For every $A \subseteq K$ non-empty and bounded above 
$$
\sup A \in K \,.
$$

:::


::: {.Theorem  #theorem-Q-not-complete}
$\Q$ is not complete. In particular, there exists a set $A \subseteq \Q$ such that 

- $A$ is non-empty,
- $A$ is bounded above,
- $\sup A$ does not exist in $\Q$. 

One of such sets is, for example,
$$
A = \{ q \in \Q  \divider q \geq 0 \,, \,\, q^2 < 2 \} \,.
$$

:::





::: Proposition
Let $(K,+,\cdot,\leq)$ be a complete ordered field. Suppose that $A \subseteq K$ is non-empty and bounded below. Then 
$$
\inf A \in K\,.
$$
:::





::: Definition
### System of Real Numbers $\R$   {#definition-R}

A system of Real Numbers is a set $\R$ with two operations $+$ and $\cdot$, and
a total order relation $\leq$, such that


- $(\R,+,\cdot, \leq)$ is an ordered field

- $\R$ sastisfies the Axiom of Completeness   

:::




### Inductive sets

::: Definition
### Inductive set
Let $S \subseteq \R$. We say that $S$ is an inductive set if they are satisfied:

- $1 \in S$,
- If $x \in S$, then $(x + 1) \in S$.

:::


::: Example

**Question.** Prove the following:

1. $\R$ is an inductive set.  

2. The set $A=\{0,1\}$ is not an inductive set.  

**Solution.**

1. We have that $1 \in \R$ by axiom (M2). Moreover $(x + 1) \in \R$ for every $x \in \R$, by definition of sum $+$.

2. We have $1 \in A$, but $(1 + 1) \notin A$, since $1 + 1 \neq 0$.

:::


::: Proposition

Let $\mathcal{M}$ be a collection of inductive subsets of $\R$. Then
$$
S := \bigcap_{M \in \mathcal{M}} \, M 
$$
is an inductive subset of $\R$.

:::


::: Definition
### Set of Natural Numbers  {#definition-natural-numbers}

Let $\mathcal{M}$ be the collection of **all** inductive subsets of $\R$. 
We define the set of natural numbers in $\R$ as 
$$
\N := \bigcap_{M \in \mathcal{M}} \, M \,.
$$

:::




::: Proposition  
### ${\N}_{\R}$ is the smallest inductive subset of $\R$   {#proposition-smallest-inductive}

Let $C \subseteq \R$ be an inductive subset. Then
$$
\N \subseteq C \,.
$$
In other words, $\N$ is the smallest inductive set in $\R$.
:::



::: {.Theorem   #theorem-n-1} 

Let $x \in \N$. Then
$$
x \geq 1 \,.
$$

:::



## Properties of $\mathbb{R}$



::: Theorem
### Archimedean Property   {#theorem-archimedean}

Let $x \in \R$ be given. Then:

1. There exists $n \in \N$ such that
$$
n > x \,.
$$

2. Suppose in addition that $x>0$. There exists $n \in \N$ such that
$$
\frac1n < x \,.
$$

:::



::: Theorem
### Archimedean Property (Alternative formulation)  {#theorem-archimedean-alternative}

Let $x,y \in \R$, with $0<x<y$. There exists $n \in \N$ such that 
$$
nx > y \,.
$$

:::



::: Theorem
### Nested Interval Property  {#theorem-nested}

For each $n \in \N$ assume given a closed interval
$$
I_n := [a_n,b_n] = \{   x \in \R \divider  a_n \leq x \leq b_n   \} \,.
$$
Suppose that the intervals are nested, that is,
$$
I_n \supset I_{n+1}\,, \quad \forall \, n \in \N \,.
$$
Then
$$
\bigcap_{n=1}^\infty I_n \neq \emptyset \,.
$${#eq-theorem-nested-proof-0}
:::






::: {.Example #example-nested-open}

**Question.** Consider the **open** intervals 
$$
I_n := \left( 0, \frac1n \right) \,.
$$
These are clearly nested
$$
I_n \supset I_{n+1}\,, \quad \forall \, n \in \N \,.
$$
Prove that
$$
\bigcap_{n=1}^\infty I_n = \emptyset \,.
$${#eq-example-nested-2}

**Solution.** Suppose by contradiction that the intersection is non-empty. Then there exists $x \in \N$
such that 
$$
x \in I_n \,, \quad \forall \, n \in \N \,.
$$
By definition of $I_n$ the above reads
$$
0 < x < \frac1n  \,, \quad \forall \, n \in \N \,.
$${#eq-example-nested}
Since $x>0$, by the Archimedean Property in Theorem \ref{theorem-archimedean} Point 2, there exists $n_0 \in \N$ such that
$$
0 < \frac{1}{n_0} < x \,.
$$
The above contradicts (@eq-example-nested). Therefore (@eq-example-nested-2) holds.
:::


### Revisiting Sup and Inf

::: Proposition 
### Characterization of Supremum  {#proposition-supremum-characterization}

Let $A \subseteq \R$ be a non-empty set. Suppose that $s \in \R$ is an upper bound for $A$. They 
are equivalent:

1. $s = \sup A$
2. For every $\e > 0$ there exists $x \in A$ such that 
$$
s - \e < x \,.
$$

:::



::: Proposition 
### Characterization of Infimum  {#prop-supremum-infimum}

Let $A \subseteq \R$ be a non-empty set. Suppose that $i \in \R$ is a lower bound for $A$. They 
are equivalent:

1. $i = \inf A$
2. For every $\e \in \R$, with $\e > 0$, there exists $x \in A$ such that 
$$
x < i + \e  \,.
$$

:::



::: {.Proposition  #proposition-interval-inf-sup}

Let $a, b \in \R$ with $a<b$. Let
$$
A:= (a,b) = \{ x \in \R \divider a < x < b \}\,.
$$
Then
$$
\inf A = a \,, \quad \sup A = b \,.
$$

:::



::: Corollary

Let $a, b \in \R$ with $a<b$. Let
$$
A:= (a,b) = \{ x \in \R \divider a < x < b \}\,.
$$
Then $\min A$ and $\max A$ do not exist.
:::


::: Corollary

Let $a, b \in \R$ with $a<b$. Let
$$
A:= [a,b) = \{ x \in \R \divider a \leq x < b \}\,.
$$
Then 
$$
\min A = \inf A = a \,, \quad \sup A = b \,,
$$ 
$\max A$ does not exist.


:::


::: Proposition

Define the set
$$
A :=  \left\{ \frac1n \divider n \in \N   \right\} \,.
$$
Then
$$
\inf A = 0 \,, \quad \sup A = \max A = 1 \,.
$$
:::


::: Proof

*Part 1.* We have
$$
\frac1n \leq 1 \,, \quad \forall \, n \in \N \,.
$$
Therefore $1$ is an upper bound for $A$. Since $1 \in A$, by definition of maximum we conclude that 
$$
\max A = 1 \,.
$$
Since the maximum exists, we conclude that also the supremum exists, and
$$
\sup A = \max A =  1 \,.
$$



*Part 2.* We have
$$
\frac1n > 0 \,, \quad \forall \, n \in \N \,,
$$
showing that $0$ is a lower bound for $A$. Suppose by contradiction that $0$ is not the infimum. Therefore $0$ is not the largest lower bound. Then there exists $\e \in \R$ such that:

- $\e$ is a lower bound for $A$, that is,
$$
\e \leq \frac1n  \,, \quad \forall \, n \in \N \,,
$${#eq-lower-bound-1-n}

- $\e$ is larger than $0$:
$$
0 < \e \,.
$$

As $\e>0$, by the Archimedean Property there exists $n_0 \in \N$ such that
$$
0 < \frac{1}{n_0} < \e \,.
$$
This contradicts (@eq-lower-bound-1-n). Thus $0$ is the largest lower bound of $A$, that is, $0 = \inf A$.


*Part 3.* We have that $\min A$ does not exist. Indeed suppose by contradiction that $\min A$ exists. Then 
$$
\min A = \inf A \,.
$$
As $\inf A = 0$ by Part 2, we conclude $\min A = 0$. As $\min A \in A$, we obtain $0 \in A$, which is a contradiction.
:::




### Cardinality


::: Definition
### Cardinality, Finite, Countable, Uncountable {#definition-cardinality}

Let $X$ be a set. The **cardinality** of $X$ is the number of elements in $X$. We denote
the cardinality of $X$ by
$$
|X| := \# \, \mbox{ of elements in } \, X \,.
$$
Further, we say that:

1. $X$ is **finite** if there exists a natural number $n \in \N$ and a bijection
$$
f \colon \{1,2,\ldots, n \} \to X \,.
$$
In particular 
$$
|X| = n \,.
$$

2. $X$ is **countable** if there exists a bijection
$$
f \colon \N \to X  \,.
$$
In this case we denote the cardinality of $X$ by
$$
|X| = |\N| \,.
$$

3. $X$ is **uncountable** if $X$ is neither finite, nor countable.

:::



::: {.Proposition #proposition-countable-subset}

Let $X$ be a countable set and $A \subseteq X$. Then either $A$ is finite or countable.

:::



::: Example

**Question.** Prove that $X = \{a,b,c\}$ is finite. 

**Solution.** Set $Y=\{ 1,2,3\}$. The function $f \colon X \to Y$ defined by
$$
f(1)=a \,, \quad f(2) = b \,, \quad f(3) = c \,,
$$
is bijective. Therefore $X$ is finite, with $|X| = 3$.

:::




::: Example

**Question.** Prove that the set of natural numbers $\N$ is countable. 

**Solution.** The function $f \colon X \to \N$ defined by
$$
f(n):=n \,,
$$
is bijective. Therefore $X = \N$ is countable.

:::



::: Example

**Question.** Let $X$ be the set of even numbers
$$
X = \{ 2n \divider n \in \N \} \,.
$$
Prove that $X$ is countable.

**Solution.** Define the map $f \colon \N \to X$ by
$$
f(n):= 2n \,.
$$
We have that:

1. $f$ is injective, because 
$$
f(m)=f(k) \, \implies \, 2m=2k \, 
\quad \, m=k \,.
$$

2. $f$ is surjective: Suppose that $m \in X$. By definition of $X$, there exists $n \in \N$ such that $m = 2n$. Therefore, $f(n) = m$.

    
We have shown that $f$ is bijective. Thus, $X$ is countable.

:::



::: Example

**Question.** Prove that the set of integers $\Z$ is countable. 

**Solution.** Define $f \colon \N \to \Z$ by 
$$
f(n):= 
\begin{cases}
\dfrac{n}{2}  & \,\, \mbox{ if } \, n \, \mbox{ even }  \\
-\dfrac{n+1}{2}  & \,\, \mbox{ if } \, n \, \mbox{ odd }  
\end{cases}
$$
For example
\begin{align*}
f(0) & = 0 \,, \quad f(1) = -1 \,, \quad f(2) = 1 \,, \quad f(3) = -2 \,, \\
f(4) & = 2 \,, \quad f(5) = -3 \,, \quad f(6) = 3 \,, \quad f(7) = -4 \,.
\end{align*}
We have:

1. $f$ is injective: Indeed, suppose that $m \neq n$. If $n$ and $m$ are both even or both odd we have, respectively
\begin{align*}
f(m) = \frac{m}{2} & \neq \frac{n}{2} = f(n)  \\
f(m) =  -\frac{m+1}{2} & \neq  - \frac{n+1}{2} = f(n) \,.
\end{align*}
If instead $m$ is even and $n$ is odd, we get
$$
f(m) = \frac{m}{2} \neq  - \frac{n+1}{2} = f(n)  \,,
$$
since the LHS is positive and the RHS is negative. The case when $m$ is odd and $n$ even is 
similar.  

2. $f$ is surjective: Let $z \in \Z$. If $z \geq 0$, then $m:=2z$ belongs to $\N$, is even, and
$$
f(m) = f(2z) = z \,.
$$
If instead $z < 0$, then $m := -2z -1$ belongs to $\N$, is odd, and
$$
f(m) = f(-2z-1) = z \,.
$$
    
Therefore $f$ is bijective, showing that $\Z$ is countable.

:::




:::  {.Proposition  #proposition-countable-union}

Let the set $A_n$ be countable for all $n \in \N$. Define
$$
A = \bigcup_{n \in \N} \, A_n \, .
$$
Then $A$ is countable.

:::





::: Theorem
### $\Q$ is countable  {#theorem-Q-countable}

The set of rational numbers $\Q$ is countable. 

:::


::: Theorem
### $\R$ is uncountable  {#theorem-R-uncountable}

The set of Real Numbers $\R$ is **uncountable**.

:::




::: Theorem

The set of irrational numbers 
$$
\mathcal{I}:=\R \smallsetminus \Q
$$
is uncountable.

:::


::: Proof

We know that $\R$ in uncountable and $\Q$ is countable. Suppose by contradiction that $\mathcal{I}$ is countable. Then
$$
\Q \cup \mathcal{I} 
$$
is countable by Proposition \ref{proposition-countable-union}, being union of countable sets. Since by definition
$$
\R = \Q \cup \mathcal{I} \,,
$$
we conclude that $\R$ is countable. Contradiction.


:::





## Complex Numbers


::: Definition
### Complex Numbers

The set of complex numbers $\C$ is defined as

$$
\C := \R + i \R  := \{x + i y  \divider x, y \in \R \} \,.
$$
For a complex number
$$
z = x + i y  \in \C
$$
we say that

- $x$ is the **real part** of $z$, and denote it by 
$$
x = \Re (z)
$$
- $y$ is the **imaginary part** of $z$, and denote it by 
$$
y = \Im (z)
$$

We say that

- If $\Re z = 0$ then $z$ is a **purely imaginary** number.
- If $\Im z = 0$ then $z$ is a **real** number.

:::


::: Definition
### Addition and multiplication in $\C$   {#definition-addition-C}

Let $z_1,z_2 \in \C$, so that 
$$
z_1 = x_1 + i y_1 \,\,, \quad z_2 = x_2 + i  y_2 \,\, ,
$$
for some $x_1,x_2,y_1,y_2 \in \R$:

1. The sum of $z_1$ and
$z_2$ is
$$
z_1 + z_2 :=\left(x_{1}+x_{2}\right) + i  \left(y_{1}+y_{2}\right) \,.
$$ 

2. The multiplication of $z_1$ and $z_2$ is 
\begin{align*}
z_1 \cdot z_2 := \left(x_{1} \cdot x_{2} - y_{1} \cdot y_{2}\right) + i \left(x_{1} \cdot y_{2} + x_{2} \cdot y_{1} \right) \,,
\end{align*}

:::



::: Example

**Question.** Compute $zw$, where
$$
z =  -2+3 i \,, \quad w = 1- i \,.
$$

**Solution.** Using the definition we compute
\begin{align*}
z \cdot w & = (-2+3 i) \cdot (1 -  i) \\ 
            & = (-2-(-3))+(2+3) i \\
            & = 1 + 5 i \, .
\end{align*}
Alternatively, we can proceed formally: We just need to recall that
$i^2$ has to be replaced with $-1$:
\begin{align*}
z \cdot w & = (-2+3 i) \cdot (1 -  i) \\ 
            & = - 2 + 2i + 3i - 3 i^2  \\
            & = (-2  + 3 ) + (  2 + 3 ) i \\
            & = 1 + 5 i \, .
\end{align*}

:::



::: Proposition
### Additive inverse in $\C$  {#proposition-C-additive-inverse}

The neutral element of addition in $\C$ is the number
$$
0 := 0 + 0 i \,.
$$
For any $z = x + i y \in \C$, the unique additive inverse is given by
$$
- z := -x - i y \,.
$$


:::


::: Proposition
### Multiplicative inverse in $\C$  {#proposition-C-multiplicative-inverse-bis}

The neutral element of multiplication in $\C$ is the number
$$
1 := 1 + 0 i \,.
$$
For any $z = x + i y \in \C$, the unique multiplicative inverse is given by 
$$
z^{-1} := \frac{x}{x^{2}+y^{2}}+ i \, \frac{-y}{x^{2}+y^{2}} \,.
$$

:::


::: Proof
It is immediate to check that $1$ is the neutral element of 
multiplication in $\C$. For the remaining part of the statement, set
$$
w := \frac{x}{x^{2}+y^{2}}+ i \, \frac{-y}{x^{2}+y^{2}} \,.
$$
We need to check that $z \cdot w = 1$
\begin{align*}
z \cdot w & = (x+i y) \cdot \left(\frac{x}{x^{2}+y^{2}}+ i \, \frac{-y}{x^{2}+y^{2}} \right) \\
& = \left(\frac{x^{2}}{x^{2}+y^{2}} - \frac{y \cdot(-y)}{x^{2}+y^{2}}\right) + i \, \left(\frac{x \cdot(-y)}{x^{2}+y^{2}}+\frac{x y}{x^{2}+y^{2}}\right) \\
& =1 \,,
\end{align*}
so indeed $z^{-1}=w$.

:::



::: Example

**Question.** Let $z = 3 + 2 i$. Compute $z^{-1}$. 


**Solution.** By the formula in Propostion \ref{proposition-C-multiplicative-inverse-bis} we immediately get
$$
z^{-1} = \frac{3}{3^{2}+2^{2}} +  \, \frac{-2}{3^{2}+2^{2}} \, i = 
\frac{3}{13}-\frac{2}{13} \, i  \,.
$$
Alternatively, we can proceed formally:
\begin{align*}
(3+2 i)^{-1} & = \frac{1}{3+2 i} \\ 
             & = \frac{1}{3+2 i} \, \frac{3-2 i}{3-2 i} \\
             & = \frac{3-2 i}{3^2+2^2} \\
             & = \frac{3}{13}-\frac{2}{13} i  \,,
\end{align*}
and obtain the same result.
:::



::: Theorem 

$(\C,+, \cdot)$ is a field.

:::



::: Example

**Question.** Let $w=1+i$ and $z=3-i$. Compute $\frac{w}{z}$.

**Solution.** We compute $w/z$ using the two options we have:

1. Using the formula for the inverse from Proposition \ref{proposition-C-multiplicative-inverse-bis} we compute
\begin{align*}
z^{-1} & = \frac{x}{x^{2}+y^{2}} + i \, \frac{-y}{x^{2}+y^{2}} \\
       & = \frac{3}{3^2 + 1^2} - i \, \frac{-1}{3^2 + 1^2} \\
       & = \frac{3}{10} + \frac{1}{10} \, i
\end{align*}
and therefore
\begin{align*}
\frac{w}{z} & = w \cdot z^{-1} \\
            & = (1 + i) \, \left(  \frac{3}{10} + \frac{1}{10} \, i \right) \\
            & = \left(\frac{3}{10}-\frac{1}{10}\right)+\left(\frac{1}{10}+\frac{3}{10}\right) i \\
            & = \frac{2}{10}+\frac{4}{10} i \\
            & = \frac{1}{5}+\frac{2}{5} i
\end{align*}

2. We proceed formally, using the 
multiplication by $1$ trick. We have
\begin{align*}
\frac{w}{z} & = \frac{1+i}{3-i}  \\
            & = \frac{1+i}{3-i} \frac{3+i}{3+i} \\
            & = \frac{3-1+(3+1) i}{3^2+1^2} \\
            & =\frac{2}{10}+\frac{4}{10} i \\
            & = \frac{1}{5}+\frac{2}{5} i
\end{align*}


:::



::: Definition 
### Complex conjugate

Let $z=x+iy$. We call the **complex conjugate** of $z$, denoted by $\bar{z}$, the complex number

$$
\bar{z}=x- i y \, .
$$


:::




::: Theorem 

For all $z_1, z_2 \in \mathbb{C}$ it holds:

- $\overline{z_1 +  z_2 }=\overline{z_1}+\overline{z_2}$

- $\overline{z_1 \cdot z_2}=\overline{z_1} \cdot \overline{z_2}$ 

:::


### The complex plane


::: Definition
### Modulus

The **modulus** of a complex number $z=x+i y$ is defined by
$$
|z|: = \sqrt{x^{2}+y^{2}} \,.
$$
:::



::: Definition
### Distance in $\C$

Given $z_1,z_2 \in \C$, we define the **distance** between $z_1$ and 
$z_2$ as the quantity
$$
|z_1 - z_2| \,.
$$

:::


::: Theorem

Given $z_1,z_2 \in \C$, we have
$$
|z_1 - z_2|  = \sqrt{ (x_1 - x_2)^2 + (y_1 - y_2)^2 }  \,.
$$

:::



::: Example

**Question.** Compute the distance between 
$$
z = 2-4 i \,, \quad 
w = -5+i \,.
$$ 

**Solution.**
The distance is
\begin{align*}
|z- w|  & = |(2-4 i)-(-5+i)| \\
        & = |7-5 i| \\
        & =\sqrt{7^{2}+(-5)^{2}} \\
        & =\sqrt{74}
\end{align*}

:::



::: Theorem 

Let $z, z_{1}, z_{2} \in \C$. Then

1. $\left|z_1 \cdot z_2\right|=\left|z_{1}\right|\left|z_{2}\right|$

2. $\left|z^{n}\right|=|z|^{n}$ for all $n \in \N$

3. $z \cdot \bar{z}=|z|^{2}$

:::



::: Theorem 
### Triangle inequality in $\C$ 

For all $x, y, z \in \C$,

1. $|x+y| \leq|x|+|y|$

2. $|x-z| \leq|x-y|+|y-z|$

:::




### Polar coordinates



::: Definition 
### Argument

Let $z \in \C$. The angle $\theta$ between the line connecting the origin and $z$ and the positive real axis is called the **argument** of $z$, and is denoted by
$$
\theta := \arg (z) \,.
$$

:::



::: Example 
We have the following arguments:
\begin{align*}
& \arg (1) = 0  & \quad & \arg (i) = \frac{\pi}{2}  \\
& \arg (-1) = \pi   & \quad & \arg (-i) = -\frac{\pi}{2}  \\
& \arg (1+i)=\frac{1}{4} \pi & \quad &  \arg (-1-i)=-\frac{3}{4} \pi
\end{align*}

:::



::: Theorem  
### Polar coordinates {#theorem-polar-coordinates}

Let $z \in \C$ with $z = x + i y$ and $z \neq 0$. Then
$$
x = \rho \cos(\theta) \,, \quad y = \rho \sin(\theta) \,,
$$
where 
$$
\rho := |z| = \sqrt{x^2 + y^2} \,, \quad 
\theta := \arg(z) \,.
$$


:::





::: Definition 
### Trigonometric form

Let $z \in \mathbb{C}$. The trigonometric form of $z$ is
$$
z = |z| \left[ \cos (\theta)+i \sin (\theta) \right] \,,
$$
where $\theta = \arg(z)$.
:::





::: {.Example   #example-trigonometric-form} 

**Question.** Suppose that $z \in \C$ has polar coordinates
$$
\rho = \sqrt{8}\,, \quad   \theta = \frac{3}{4} \pi \,.
$$ 
Therefore, the trigonometric form of $z$ is
$$
z = \sqrt{8}  \left[ \cos \left( \frac{3}{4} \pi \right) + i \sin \left( \frac{3}{4} \pi \right)   \right] \,.
$$
Write $z$ in cartesian form.

**Solution.** We have
\begin{gather*}
x = \rho \cos (\theta) = \sqrt{8} \cos \left( \frac{3}{4} \pi \right) = - \sqrt{8} \cdot \frac{\sqrt{2}}{2} = -2 \\
y = \rho \sin (\theta) = \sqrt{8} \sin \left( \frac{3}{4} \pi \right) = \sqrt{8} \cdot  \frac{\sqrt{2}}{2} = 2 \,.
\end{gather*}
Therefore, the cartesian form of $z$ is
$$
z = x + i y = - 2 + 2 i \,.
$$

:::


::: Corollary
### Computing $\arg(z)$   {#corollary-arg}

Let $z \in \C$ with $z = x + i y$ and $z \neq 0$. Then
$$
\arg(z) = 
\begin{cases}
\arctan \left(  \dfrac{y}{x}   \right)  &  \,\, \mbox{ if }  x>0 \\
\arctan \left(  \dfrac{y}{x}   \right) + \pi   &  \,\, \mbox{ if }  x<0\,\, \mbox{and} \,\, y \geq 0 \\
\arctan \left(  \dfrac{y}{x}   \right) - \pi   &  \,\, \mbox{ if }  x<0\,\, \mbox{and} \,\, y < 0 \\
\dfrac{\pi}{2}    &  \,\, \mbox{ if }  x=0\,\, \mbox{and} \,\, y > 0 \\
-\dfrac{\pi}{2}    &  \,\, \mbox{ if }  x=0\,\, \mbox{and} \,\, y < 0 \\
\end{cases}
$$
where $\arctan$ is the inverse of $\tan$.

:::




::: Example 

**Question.** Compute the arguments of the complex numbers 
$$
z = 3+4 i\,, \quad \bar{z} = 3-4 i \,, \quad  - \bar{z} = -3+4 i \,, \quad - z= -3-4 i \,.
$$ 

**Solution.** Using the formula for $\arg$ in Corollary \ref{corollary-arg} we have
\begin{align*}
\arg (3+4 i) & =\arctan \left(\frac{4}{3}\right) \\
\arg (3-4 i) & =\arctan \left(-\frac{4}{3}\right) = -\arctan \left(\frac{4}{3}\right)  \\
\arg (-3+4 i) & = \arctan \left(-\frac{4}{3}\right) + \pi = - \arctan \left(\frac{4}{3}\right) + \pi \\
\arg (-3-4 i) & = \arctan \left(\frac{4}{3}\right) - \pi
\end{align*}

:::





### Exponential form


::: Theorem 
### Euler's identity   {#theorem-euler-identity}

For all $\theta \in \R$ it holds
$$
e^{i \theta}=\cos (\theta)+ i \sin (\theta) \,.
$$

:::



::: Theorem 
For all $\theta \in \R$ it holds
$$
\left|e^{i \theta}\right|=1 \,.
$$

:::




::: Theorem

Let $z \in \C$ with $z = x+iy$ and $z \neq 0$. Then
$$
z = \rho e^{i\theta}\,,
$$
where 
$$
\rho := |z| =  \sqrt{x^2 + y^2} \,, \qquad 
\theta := \arg(z) \,.
$$

:::




::: Definition 
### Exponential form

The **exponential form** of a complex number $z \in \C$ is 
$$
z= \rho e^{i\theta} = |z| \, e^{i \arg(z)}  \,.
$$

:::



::: {.Example #example-exponential-form}

**Question.** Write the number 
$$
z=-2+2 i
$$ 
in exponential form.

**Solution.** From Example \ref{example-trigonometric-form} we know that $z = -2+2i$
can be written in trigonometric form as
$$
z = \sqrt{8}  \left[ \cos \left( \frac{3}{4} \pi \right) + i \sin \left( \frac{3}{4} \pi \right)   \right] \,.
$$
By Euler's identity we hence obtain the exponential form
$$
z=\sqrt{8} e^{i \frac{3}{4} \pi} \,.
$$
:::


::: Remark
### Periodicity of exponential

For all $k \in \Z$ we have
$$
e^{i \theta}=e^{i(\theta+2 \pi k)} \,,
$${#eq-exponential-periodic}
meaning that the complex exponential is $2\pi$-periodic.


:::



::: {.Proposition #proposition-complex-exponential}

Let $z, z_1,z_2 \in \C$ and suppose that
$$
z= \rho e^{i \theta} \,, \quad 
z_1 = \rho_1 e^{i \theta_1}\,, \quad 
z_2 = \rho_2 e^{i \theta_2}\,.
$$
We have
$$
z_1 \cdot z_2 = \rho_1 \rho_2 e^{i (\theta_1 + \theta_2)}  \,, \quad 
z^n = \rho^n  e^{i n \theta} \,,
$$
for all $n \in \N$.
:::


::: Example 

**Question.** Compute $(-2+2 i)^{4}$.

**Solution.** We have two possibilities:

1. Use the binomial theorem:
\begin{align*}
(-2+2 i)^{4} & =(-2)^{4}+\left(\begin{array}{l}
4 \\
1
\end{array}\right)(-2)^{3} \cdot 2 i+\left(\begin{array}{l}
4 \\
2
\end{array}\right)(-2)^{2} \cdot(2 i)^{2} \\
& \quad +\left(\begin{array}{l}
4 \\
3
\end{array}\right)(-2) \cdot(2 i)^{3}+(2 i)^{4} \\
& =16-4 \cdot 8 \cdot 2 i-6 \cdot 4 \cdot 4+4 \cdot 2 \cdot 8 i+16 \\
& =16-64 i-96+64 i+16=-64 \,.
\end{align*}

2. A much simpler calculation is possible by using the exponential form: We know that
$$
-2+2 i = \sqrt{8} e^{i \frac{3}{4} \pi} 
$$
by Example \ref{example-exponential-form}. Hence
$$
(-2+2 i)^{4}=\left(\sqrt{8} e^{i \frac{3}{4} \pi}\right)^{4}=8^{2} e^{i 3 \pi}=-64 \,,
$$
where we used that 
$$
e^{i 3 \pi} = e^{i \pi} = \cos(\pi) + i \sin(\pi) = - 1
$$
by $2\pi$ periodicity of $e^{i\theta}$ and Euler's identity. 
:::


::: Definition
### Complex exponential

The complex exponential of $z \in \C$ is defined as
$$
e^z = |z| e^{i\theta} \,, \quad \theta = \arg(z) \,.
$$

:::



::: Theorem

Let $z,w \in \C$. Then
$$
e^{z+w} = e^z e^w \,, \quad (e^z)^{w} = e^{zw} \,.
$${#eq-complex-exponential}

:::




::: Example 

**Question.** Compute $i^{i}$.

**Solution.** We know that 
$$
|i| = 1 \,, \quad \arg(i) = \frac{\pi}{2} \,.
$$
Hence we can write $i$ in exponential form
$$
i= |i| e^{i\arg(i)} = e^{i \frac{\pi}{2}} \,.
$$ 
Therefore
$$
i^{i}=\left(e^{i \frac{\pi}{2}}\right)^{i}=e^{i^2\frac{\pi}{2}}=e^{-\frac{\pi}{2}} \,.
$$

:::



### Fundamental Theorem of Algebra


::: Theorem 
### Fundamental theorem of algebra   {#theorem-fta}

Let $p_{n}(z)$ be a polynomial of degree $n$ with complex coefficients, i.e.,
$$
p_{n}(z)=a_{n} z^{n}+a_{n-1} z^{n-1}+\ldots+a_{1} z+a_{0},
$$
for some coefficients $a_{n}, \ldots, a_{0} \in \C$ with $a_{n} \neq 0$. There exist 
$$
z_{1}, \ldots, z_{n} \in \C
$$ 
solutions to the polynomial equation
$$
p_n(z) = a_{n} z^{n}+a_{n-1} z^{n-1}+\ldots+a_{1} z+a_{0}=0 \,.
$${#eq-fta}
In particular, $p_n$ factorizes as
$$
p_{n}(z)=a_{n}\left(z-z_{1}\right)\left(z-z_{2}\right) \cdots\left(z-z_{n}\right) \,.
$${#eq-fta-0}


:::



::: Example 

**Question.** Find all the complex solutions to
$$
z^{2}=-1
$${#eq-fta-example-1}

**Solution.** The equation $z^2 = -1$ is equivalent to
$$
p(z) = 0 \,, \quad p(z):=z^{2}+1  \,.
$$
Since $p$ has degree $n=2$, the Fundamental Theorem of Algebra tells us that there are two solutions to (@eq-fta-example-1). We have already seen that these two solutions are $z=i$ and $z=-i$. Then $p$ factorizes as
$$
p(z) = z^{2} + 1 = (z-i)(z+i) \,.
$$
:::


::: {.Example   #example-degree-4}

**Question.** Find all the complex solutions to
$$
z^{4}-1=0 \,.
$${#eq-fta-example-2}

**Solution** The associated polynomial equation is 
$$
p(z) = 0 \,, \quad p(z) := z^4 - 1 \,. 
$$
Since $p$ has degree $n=4$, the Fundamental Theorem of Algebra tells us that there are $4$ solutions to (@eq-fta-example-2). Let us find such solutions. We use the well known identity
$$
a^2-b^2 = (a+b)(a-b) \,, \quad \forall \, a,b \in \R \,,
$$
to factorize $p$. We get:
$$
p(z) = (z^4-1) = (z^2+1)(z^2-1) \,.
$$
We know that 
$$
z^2 + 1 = 0 
$$
has solutions $z = \pm i$. Instead  
$$
z^2 - 1 = 0 
$$
has solutions $x = \pm 1$. Hence, the four solutions of (@eq-fta-example-2) are given by 
$$
z=1,-1, i,-i \,,
$$
and $p$ factorizes as
$$
p(z) = z^4 - 1 = (z-1)(z+1)(z-i)(z+i) \,.
$$

:::


::: Definition

Suppose that the polynomial $p_n$ factorizes as 
$$
p_n(z) = a_n (z-z_1)^{k_1} (z-z_2)^{k_2} \cdots (z-z_m)^{k_m} 
$$
with $a_n \neq 0$, $z_1,\ldots, z_m \in \C$ and $k_1, \ldots , k_m \in \N$, $k_i \geq 1$. In this case $p_n$ has degree
$$
n = k_1 + \ldots + k_m = \sum_{i=1}^m k_i \,.
$$
Note that $z_i$ is solves the equation
$$
p_n(z) = 0
$$
exactly $k_i$ times. We call $k_i$ the **multiplicity** of the solution $z_i$.
:::

::: {.Example  #example-multiplicity}

The equation
$$
(z-1)(z-2)^{2}(z+i)^{3}=0
$$
has 6 solutions: 

- $z=1$ with multiplicity $1$
- $z=2$ with multiplicity $2$ 
- $z=-i$ with multiplicity $3$

:::




### Solving polynomial equations



::: Proposition
### Quadratic formula    {#proposition-quadratic-formula}

Let $a, b, c \in \R, a \neq 0$ and consider the equation
$$
ax^2 + bx + c = 0 \,.
$${#eq-quadratic-formula}
Define 
$$
\Delta := b^2 - 4 ac \in \R \,.
$$
The following hold:

1. If $\Delta > 0$ then (@eq-quadratic-formula) has two distinct real solutions $z_1,z_2 \in \R$ given by
$$
z_1 = \frac{-b - \sqrt{\Delta}}{2 a} \,, 
\quad 
z_2 = \frac{-b + \sqrt{\Delta}}{2 a} \,.
$$
2. If $\Delta = 0$ then (@eq-quadratic-formula) has one real solution $z \in \R$ with multiplicity $2$. Such solution is given by
$$
z = z_1 = z_2 = \frac{-b}{2 a} \,.
$$
3. If $\Delta < 0$ then (@eq-quadratic-formula) has two distinct complex solutions $z_1,z_2 \in \C$ given by 
$$
z_1 = \frac{-b - i\sqrt{-\Delta}}{2 a} \,, 
\quad 
z_2 = \frac{-b + i\sqrt{-\Delta}}{2 a} \,,
$$
where $\sqrt{-\Delta} \in \R$, since $-\Delta>0$.

In all cases, the polynomial at (@eq-quadratic-formula) factorizes as
$$
a z^{2}+b z+c = a (z-z_1)(z-z_2) \,.
$$

:::




::: Example 


**Question.** Solve the following equations:

1. $3 z^{2}-6 z+2 = 0$
2. $4 z^{2}-8 z+4=0$
3. $z^{2}+2 z+3=0$

**Solution.**

1. We have that
$$
\Delta = (-6)^{2}-4 \cdot 3 \cdot 2 = 12 > 0
$$
Therefore the equation has two distinct real solutions, given by
$$
z=\frac{-(-6) \pm \sqrt{12}}{2 \cdot 3}=\frac{6 \pm \sqrt{12}}{6}=1 \pm \frac{\sqrt{3}}{3}
$$
In particular we have the factorization
$$
3 z^{2}-6 z+2  = 3 \left( z - 1 - \frac{\sqrt{3}}{3} \right) \left( z - 1 + \frac{\sqrt{3}}{3} \right) \,.
$$



2. We have that 
$$
\Delta = (-8)^{2}-4 \cdot 4 \cdot 4 = 0 \,.
$$
Therefore there exists one solution with multiplicity $2$. This
is given by
$$
z=\frac{-(-8)}{2 \cdot 4} = 1 \,.
$$
In particular we have the factorization
$$
4 z^{2}-8 x+4 = 4 (z-1)^2 \,.
$$



3. We have
$$
\Delta = 2^{2}-4 \cdot 1 \cdot 3 = - 8 < 0 \,.
$$
Therefore there are two complex solutions given by
$$
z=\frac{-2 \pm i \sqrt{8}}{2 \cdot 1} = -1 \pm i \sqrt{2}  \,.
$$
In particular we have the factorization
$$
z^{2}+2 z+3 = (z + 1 - i \sqrt{2}) (z + 1 + i\sqrt{2}) \,.
$$

:::


::: Proposition   
### Quadratic formula with complex coefficients {#proposition-quadratic-formula-C}

Let $a, b, c \in \C, a \neq 0$. The two solutions to 
$$
a z^{2}+b z + c=0
$$ 
are given by
$$
z_1 = \frac{-b + S_1}{2 a} \,, 
\quad 
z_2 = \frac{-b + S_2}{2 a} \,, 
$$
where $S_1$ and $S_2$ are the two solutions to
$$
z^2 = \Delta \,, \quad \Delta := b^2 - 4ac \,.
$$

:::





::: Example

**Question** Find all the solutions to
$$
\frac{1}{2} z^{2}-(3+i) z+(4-i)=0 \,.
$${#eq-example-complex-delta}

**Solution.** We have
\begin{align*}
\Delta & = (-(3+i))^{2}-4 \cdot \frac{1}{2} \cdot(4-i) \\
       & = 8+6 i-8+2 i \\
       & =8 i \,.
\end{align*}
Therefore $\Delta \in \C$. We have to find solutions $S_1$ and $S_2$ to the equation
$$
z^2 = \Delta = 8i \,.
$${#eq-example-complex-delta-2}
We look for solutions of the form $z=a+ i b$. Then we must have that
$$
z^{2}=(a+ ib)^{2}=a^{2}-b^{2}+2 a b i = 8 i \,.
$$
Thus
$$
a^{2}-b^{2}=0 \,, \quad 2 a b = 8  \,.
$$ 
From the first equation we conclude that $|a|=|b|$. From the second equation we have that $ab=4$, and therefore $a$ and $b$ must have the same sign. Hence $a=b$, and 
$$
2 a b = 8 \quad \implies \quad a = b = \pm 2 \,.
$$
From this we conclude that the solutions to (@eq-example-complex-delta-2)
are 
$$
S_{1} = 2+2 i \,, \quad  S_{2}=-2-2 i \,. 
$$
 Hence the solutions to (@eq-example-complex-delta) are
\begin{align*}
z_1 & = \frac{3+i+S_{1}}{2 \cdot \frac{1}{2}}  = 3 + i + S_{1} \\
    & = 3 + i + 2 + 2i = 5 + 3i \,, 
\end{align*}
and 
\begin{align*}
z_2 & = \frac{3+i+S_{2}}{2 \cdot \frac{1}{2}}  = 3+i+S_{2} \\
    & = 3+i -2 - 2i  = 1 - i \,. 
\end{align*}
In particular, the given polynomial factorizes as
\begin{align*}
\frac{1}{2} z^{2}-(3+i) z+(4-i) & = \frac12 (z - z_1)(z-z_2) \\
                                & = \frac12 (z - 5 - 3i)(z - 1 + i) \,. 
\end{align*}

:::



::: Example 

**Question.** Consider the equation
$$
z^{3}-7 z^{2}+6 z=0 \,.
$$ 

1. Check whether $z=0,1,-1$ are solutions.
2. Using your answer from Point 1, and polynomial division, find all the solutions.

**Solution.**

1. By direct inspection we see that $z=0$ and $z=1$ are solutions.

2. Since $z = 0$ is a solution, we can factorize
$$
z^{3}-7 z^{2}+6 z=z\left(z^{2}-7 z+6\right) \,.
$$
We could now use the quadratic formula on the term $z^{2}-7 z+6$ to find the remaining two roots. However, we have already observed that $z=1$ is a solution. Therefore $z-1$ divides $z^{2}-7 z+6$. Using polynomial long division, we find that
$$
\frac{z^{2}-7 z+6}{z-1}=z-6 \,.
$$
Therefore the last solution is $z=6$, and
$$
z^{3}-7 z^{2}+6 z=z(z-1)(z-6) \,.
$$

:::


::: Example

**Question.** Find all the complex solutions to
$$
z^{3}-7 z+6=0 \,.
$$ 

**Solution.** It is easy to see $z=1$ is a solution. This means that $z-1$ divides $z^{3}-7 z+6$. By using polynomial long division, we compute that
$$
\frac{z^{3}-7 z+6}{z-1}=z^{2}+z-6 \,.
$$
We are now left to solve
$$
z^{2}+z-6 = 0\,.
$$
Using the quadratic formula, we see that the above is solved by $z=2$ and $z=-3$.
Therefore the given polynomial factorizes as
$$
z^{3}-7 z+6 = (z-1)(z-2)(z+3) \,.
$$

:::




### Roots of unity

::: Theorem

Let $n \in \N$ and consider the equation
$$
z^{n}=1 \,.
$${#eq-root-unity-1}
All the $n$ solutions to (@eq-root-unity-1) are given by
$$
z_k = \exp \left(i \frac{2 \pi k}{n}\right) \,, \quad k = 0, \ldots, n-1 \,,
$$
where $\exp(x)$ denotes $e^x$.

:::


::: Definition 

The $n$ solutions to 
$$
z^{n}=1
$$ 
are called the **roots of unity**.

:::


::: Example 

**Question.** Find all the solutions to
$$
z^{4}=1 \,.
$$ 

**Solution.** The $4$ solutions are given by
$$
z_k = \exp \left(i \frac{2 \pi k}{4} \right) = \exp \left(i \frac{\pi k}{2} \right)  \,,
$$
for $k=0,1,2,3$. We compute:
\begin{align*}
z_0 & = e^{i 0} = 1 \,, & \quad & z_1 = e^{i \frac{\pi}{2}}=i \,, \\ 
z_2 & = e^{i \pi}=-1 \,, & \quad & z_3 = e^{i \frac{3 \pi}{2}}=-i \, .
\end{align*}
Note that for $k=4$ we would again get the solution $z=e^{i 2 \pi}=1$.

:::


::: Example 

**Question.** Find all the solutions to 
$$
z^{3}=1 \,.
$$ 

**Solution.** The $3$ solutions are given by
$$
z_k = \exp \left( i \frac{2 \pi k}{3} \right) \,,
$$
for $k=0,1,2$. We compute:
$$
z_0=e^{i 0}=1, \quad z_1=e^{i \frac{2 \pi}{3}}, \quad z_2=e^{i \frac{4 \pi}{3}} .
$$
We can write $z_1$ and $z_2$ in cartesian form:
$$
z_1 = e^{i \frac{2 \pi}{3}}=\cos \left(\frac{2 \pi}{3}\right)+i \sin \left(\frac{2 \pi}{3}\right)=-\frac{1}{2}+\frac{\sqrt{3}}{2} i
$$
and
$$
z_2 = e^{i \frac{4 \pi}{3}}=\cos \left(\frac{4 \pi}{3}\right)+i \sin \left(\frac{4 \pi}{3}\right)=-\frac{1}{2}-\frac{\sqrt{3}}{2} i \,.
$$

:::




### Roots in $\C$ {#sec-roots-2}




::: Theorem

Let $n \in \N$, $c \in \C$ and consider the equation
$$
z^{n}=c \,.
$${#eq-root-C}
All the $n$ solutions to (@eq-root-C) are given by
$$
z_k = \sqrt[n]{|c|} \, \exp \left(i \, \frac{\theta + 2 \pi k}{n}\right) \,, \quad k = 0, \ldots, n-1 \,,
$$
where $\sqrt[n]{|c|}$ is the $n$-th root of the real number $|c|$, and $\theta = \arg(c)$.

:::


::: Example

**Question.** Find all the $z \in \C$ such that
$$
z^{5}=-32 \,.
$$

**Solution.** Let $c = -32$. We have
$$
|c| = |-32|=32=2^{5}\,, \quad \theta = \arg (-32)=\pi \,.
$$ 
The $5$ solutions are given by
$$
z_k =  \left(2^{5}\right)^{\frac{1}{5}} \exp \left(i \pi \, \frac{1+2 k}{5} \right) \,, \quad k \in \Z \,,
$$
for $k=0,1,2,3,4$. We get
\begin{align*}
z_0 & = 2 e^{i \frac{\pi}{5}} \,  & \quad & z_1 = 2 e^{i \frac{3 \pi}{5}}  \\ 
z_2 & = 2 e^{i \pi}=-2 \,  & \quad & z_3=2 e^{i \frac{7 \pi}{5}}  \\
z_4 &= 2 e^{i \frac{9 \pi}{5}}  & \quad & 
\end{align*}

:::


::: Example 

**Question.** Find all the $z \in \C$ such that
$$
z^{4}=9\left(\cos \left(\frac{\pi}{3}\right)+i \sin \left(\frac{\pi}{3}\right)\right) \,.
$$

**Solution.** Set 
$$
c:=9\left(\cos \left(\frac{\pi}{3}\right)+i \sin \left(\frac{\pi}{3}\right)\right) \,.
$$
The complex number $c$ is already in the trigonometric form, so that we can immediately obtain
$$
|c| = 9 \,, \quad \theta = \arg(c) = \frac{\pi}{3} \,.
$$
The $4$ solutions are given by
\begin{align*}
z_k & = \sqrt[4]{9} \, \exp \left( i \,  \frac{ \pi/3 + 2 \pi k}{4} \right) \\
& = \sqrt{3} \exp \left(  i \pi \, \frac{1+6 k}{12} \right) 
\end{align*}
for $k=0,1,2,3$. We compute
\begin{align*}
z_0 & = \sqrt{3} e^{i \pi \frac{1}{12}} & \quad & z_1 = \sqrt{3} e^{i \pi \frac{7}{12}} \\
z_2 & = \sqrt{3} e^{i \pi \frac{13}{12}}  & \quad &  z_3 = \sqrt{3} e^{i \pi \frac{19}{12}} 
\end{align*}

:::








## Sequences in $\R$


::: Definition 
### Convergent sequence  {#definition-convergent-sequence}

The real sequence $(a_n)$ **converges** to $a$, or equivalently has limit $a$, denoted by
$$
\lim_{n \rightarrow \infty} a_{n}=a \,,
$$
if for all $\e \in \mathbb{R}, \e>0$, there exists $N \in \N$ such that for all $n \in \N, n \geq N$ it holds that 
$$
\left|a_{n}-a\right| < \e \,.
$$
Using quantifiers, we can write this as
$$
\forall \, \e>0 , \, \exists \, N \in \N \st \forall \, n \geq N \,, \,\left|a_{n}-a\right| < \e \,.
$$
The sequence $\left(a_{n}\right)_{n \in \N}$ is **convergent** if it admits limit.

:::


::: {.Theorem  #theorem-one-over-np}
Let $p>0$. Then
$$
\lim _{n \rightarrow \infty} \frac{1}{n^{p}}=0 \,.
$$
:::

::: Proof

Let $p>0$. We have to show that
$$
\forall \e>0 \,, \, \exists \, N \in \N \st  \forall \, n \geq N \,, \, \left|\frac{1}{n^{p}}-0\right| < \e \,.
$$
Let $\e>0$. Choose $N \in \N$ such that 
$$
N > \frac{1}{\e^{1 / p}} \,.
$${#eq-theorem-one-over-np-1}
Let $n \geq N$. Since $p>0$, we have $n^{p} \geq N^{p}$, which implies 
$$
\frac{1}{n^p} \leq \frac{1}{N^p} \,.
$$
By (@eq-theorem-one-over-np-1) we deduce
$$
\frac{1}{N^p} < \e \,.
$$
Then
$$
\left|\frac{1}{n^{p}}-0\right|=\frac{1}{n^{p}} \leq \frac{1}{N^{p}} < \e \,.
$$

:::



::: Example 

**Question.** Using the definition of convergence, prove that
$$
\lim_{n \to \infty} \frac{n}{2n+3} = \frac{1}{2} \,.
$$

**Solution.**

1. *Rough Work:* Let $\e>0$. We want to find $N \in \N$ such that
$$
\left|\frac{n}{2n+3}-\frac{1}{2}\right| < \e \,, \quad \forall \, n \geq N \,.
$$
To this end, we compute:
\begin{align*}
\left|\frac{n}{2 n+3}-\frac{1}{2}\right| & 
=\left|\frac{2n -(2n + 3)}{2(2n +3)}\right| \\
& =\left|\frac{- 3}{4n + 6}\right| \\
& = \frac{3}{4n + 6} \,.
\end{align*}
Therefore 
\begin{align*}
\left|\frac{n}{2n+3}-\frac{1}{2}\right| < \e
\quad \iff &  \quad
\frac{3}{4n + 6} < \e \\
\quad \iff &  \quad
\frac{4n + 6}{3} > \frac{1}{\e} \\
\quad \iff &  \quad
4n + 6 > \frac{3}{\e} \\
\quad \iff &  \quad
4n  > \frac{3}{\e} - 6 \\
\quad \iff &  \quad
n  > \frac{3}{4\e} - \frac{6}{4} \,.
\end{align*}
Looking at the above equivalences, it is clear that $N \in \N$ has to be chosen so that
$$
N  > \frac{3}{4\e} - \frac{6}{4} \,.
$$


2. *Formal Proof:* We have to show that
$$
\forall \e>0 \,, \, \exists \, N \in \N \st  \forall \, n \geq N \,, \, \left|\frac{n}{2n+3}-\frac{1}{2}\right| < \e  \,.
$$
Let $\e>0$. Choose $N \in \N$ such that
$$
N > \frac{3}{4\e} - \frac{6}{4}   \,.
$${#eq-example-limit-1}
By the rough work shown above, inequality (@eq-example-limit-1) is equivalent to 
$$
 \frac{3}{4N + 6} < \e \,.
$$
Let $n \geq N$. Then
\begin{align*}
\left|\frac{n}{2n+3}-\frac{1}{2}\right| 
& = \frac{3}{4 n+ 6 } \\
& \leq \frac{3}{4 N+ 6 } \\
& < \e \,,
\end{align*}
where in the third line we used that $n \geq N$.

:::



::: Definition
### Divergent sequence

We say that a sequence $\left(a_{n}\right)_{n \in \N}$ in $\R$ is **divergent** if it is not convergent.

:::




::: {.Theorem #theorem-1-minus-n}
Let $\left(a_{n}\right)$ be the sequence defined by
$$
a_{n}=(-1)^{n} \,.
$$
Then $\left(a_{n}\right)$ does not converge. 

:::



::: Proof

Suppose by contradiction that $a_n \to a$ for some $a \in \R$. Let
$$
\e :=\frac12 \,.
$$
Since $a_n \to a$, there exists $N \in \N$ such that 
$$
|a_n - a| < \e = \frac13  \, \quad \forall \, n \geq N \,.
$$
If we take $n = 2N$, then $n \geq N$ and
$$
|a_{2N} - a| = | 1 - a | < \frac12 \,. 
$$
If we take $n = 2N + 1$, then $n \geq N$ and
$$
|a_{2N+1} - a| = | -1 - a | < \frac12 \,. 
$$
Therefore 
\begin{align*}
2 & = |  (1 - a) - (-1 - a) | \\
  & \leq |1 - a| + |-1 - a| \\
  & < \frac12 + \frac12 = 1 \,,
\end{align*}
which is a contradiction. Hence $(a_n)$ is divergent.

:::


::: Theorem 
### Uniqueness of limit  {#theorem-uniqueness-limit}

Let $\left(a_{n}\right)_{n \in \N}$ be a sequence. Suppose that 
$$
\lim_{n \rightarrow \infty} a_{n} = a \,, \quad 
\lim_{n \rightarrow \infty} a_{n} = b \,.
$$
Then $a=b$.
:::





::: Definition 
### Bounded sequence  {#definition-bounded-sequence}

A sequence $\left(a_{n}\right)_{n \in \N}$ is called **bounded** if there exists a constant $M \in \R$, with $M>0$, such that
$$
\left|a_{n}\right| \leq M \,, \quad \forall \, n \in \N \,.
$$

:::


::: {.Theorem  #theorem-convergent-bounded}

Every convergent sequence is bounded.

:::



::: Example

The sequence 
$$
a_n = (-1)^n
$$
is bounded but not convergent.

:::


::: {.Corollary   #corollary-convergent-bounded}

If a sequence is not bounded, then the sequence does not converge.

:::


::: Remark

For a sequence $(a_n)$ to be unbounded, it means that
$$
\forall \, M > 0 \,, \,\,  \exists \, n \in \N \st \left|a_{n}\right| > M \,.
$$

:::




::: Theorem 

For all $p>0$, the sequence 
$$
a_n = n^p
$$
does not converge.

:::



::: Theorem

The sequence 
$$
a_n  = \log n
$$
does not converge.

:::


::: Theorem 
### Algebra of limits {#theorem-algebra-limits} 

Let $\left(a_{n}\right)_{n \in \mathbb{N}}$ and $\left(b_{n}\right)_{n \in \mathbb{N}}$ be sequences in $\mathbb{R}$. Suppose that
$$
\lim_{n \rightarrow \infty} a_{n}=a \,, \quad  \lim_{n \rightarrow \infty} b_{n}=b \,,
$$
for some $a,b \in \R$. Then,

1. Limit of sum is the sum of limits:
$$
\lim_{n \rightarrow \infty}\left(a_{n} \pm b_{n}\right)=a \pm b
$$

2. Limit of product is the product of limits: 
$$
\lim _{n \rightarrow \infty}\left(a_{n}  b_{n}\right) = a  b 
$$

3. If $b_{n} \neq 0$ for all $n \in \mathbb{N}$ and $b \neq 0$, then 
$$
\lim_{n \rightarrow \infty} \left(\frac{a_{n}}{b_{n}}\right)=\frac{a}{b} 
$$

:::






::: {.Example  #example-limit-ploynomial}

**Question.** Prove that 
$$
\lim_{n \to \infty} \, \frac{3 n}{7 n+4} = \frac{3}{7} \,.
$$


**Solution.** We can rewrite
$$
\frac{3 n}{7 n+4}=\frac{3}{7+\dfrac{4}{n}}
$$
From Theorem \ref{theorem-one-over-np}, we know that 
$$
\frac{1}{n} \rightarrow 0 \,.
$$
Hence, it follows from Theorem \ref{theorem-algebra-limits} Point 2 that 
$$
\frac{4}{n} = 4 \cdot \frac1n \rightarrow 4 \cdot 0 = 0 \,.
$$
By Theorem \ref{theorem-algebra-limits} Point 1 we have
$$
7 + \frac{4}{n} \rightarrow  7 + 0 = 7 \,.
$$
Finally we can use Theorem \ref{theorem-algebra-limits} Point 3 to infer
$$
\frac{3 n}{7 n+4}=\frac{3}{7+\dfrac{4}{n}} \rightarrow \frac{3}{7} \,.
$$

:::



::: {.Example #example-algebra-of-limits-2}

**Question.** Prove that
$$
\lim_{n \rightarrow \infty} \frac{n^{2}-1}{2 n^{2}-3} = \frac{1}{2} \,.
$$

**Solution.** Factor $n^2$ to obtain
$$
\frac{n^{2}-1}{2 n^{2}-3} = \frac{1-\dfrac{1}{n^{2}}}{2-\dfrac{3}{n^{2}}} \,.
$$
By Theorem \ref{theorem-one-over-np} we have
$$
\frac{1}{n^2} \to 0 \,.
$$
We can then use the Algebra of Limits Theorem \ref{theorem-algebra-limits} Point 2 to infer
$$
\frac{3}{n^2} \to 3 \cdot 0 = 0
$$
and Theorem \ref{theorem-algebra-limits} Point 1 to get
$$
1 - \frac{1}{n^2} \to 1 - 0 = 1 \,, \quad 
2 - \frac{3}{n^2} \to 2 - 0 = 2 \,.
$$
Finally we use Theorem \ref{theorem-algebra-limits} Point 3 and conclude
$$
 \frac{1-\dfrac{1}{n^{2}}}{2-\dfrac{3}{n^{2}}} \to \frac{1}{2} \,.
$$
Therefore
$$
\lim_{n \to \infty } \, \frac{n^{2}-1}{2 n^{2}-3} = \lim_{n \to \infty} \, \frac{1-\dfrac{1}{n^{2}}}{2-\dfrac{3}{n^{2}}} = \frac{1}{2} \,.
$$

:::




::: Example 

**Question.** Prove that the sequence
$$
a_n = \frac{4 n^{3}+8 n+1}{7 n^{2}+2 n+1}
$$
does not converge.

**Solution.** To show that the sequence $\left(a_n\right)$ does not converge, we divide by the largest power in the denominator, which in this case is $n^2$
\begin{align*}
a_n & = \frac{4 n^{3}+8 n+1}{7 n^{2}+2 n+1} \\
    & =\frac{4 n+ \dfrac{8}{n}  +  \dfrac{1}{n^{2}} }{7+  \dfrac{2}{n}  +  \dfrac{1}{n^{2}} } \\
    & = \frac{b_n}{c_n}
\end{align*}
where we set 
$$
b_n := 4 n+ \dfrac{8}{n}  +  \dfrac{1}{n^{2}}\,, \quad
c_n := 7 + \dfrac{2}{n}  +  \dfrac{1}{n^{2}} \,.
$$
Using the Algebra of Limits Theorem \ref{theorem-algebra-limits} we see that
$$
c_n = 7+  \dfrac{2}{n}  +  \dfrac{1}{n^{2}}  \to 7 \,.
$$
Suppose by contradiction that
$$
a_n \to a
$$
for some $a \in \R$. Then, by the Algebra of Limits, we would infer
$$
b_n = c_n \cdot a_n \to 7 a \,,
$$
concluding that $b_n$ is convergent to $7a$. We have that
$$
b_n = 4n + d_n \,, \quad d_n := \dfrac{8}{n}  +  \dfrac{1}{n^{2}} \,.
$$
Again by the Algebra of Limits Theorem \ref{theorem-algebra-limits} we get that 
$$
d_n =  \dfrac{8}{n}  +  \dfrac{1}{n^{2}} \to 0 \,,
$$
and hence
$$
4n = b_n - d_n \to 7a - 0 = 7a \,.
$$
This is a contradiction, since the sequence $(4n)$ is unbounded, and hence cannot be convergent. Hence $(a_n)$ is not convergent.
:::


::: Example 

**Question.** Define the sequence
$$
 a_n := \frac{2 n^{3}+7 n+1}{5 n+9} \cdot \frac{8 n+9}{6 n^{3}+8 n^{2}+3} \,.
$$
Prove that 
$$
\lim_{n \to \infty}  a_n = \frac{8}{15} \,.
$$


**Solution.** The first fraction in $(a_n)$ does not converge, as it is unbounded. Therefore we cannot use Point 2 in Theorem \ref{theorem-algebra-limits} directly. However, we note that
\begin{align*}
a_{n} & =\frac{2 n^{3}+7 n+1}{5 n+9} \cdot \frac{8 n+9}{6 n^{3}+8 n^{2}+3} \\
& = \frac{8 n+9}{5 n+9} \cdot \frac{2 n^{3}+7 n+1}{6 n^{3}+8 n^{2}+3} \,.
\end{align*}
Factoring out $n$ and $n^3$, respectively, and using the Algebra of Limits, we see that
$$
\frac{8 n+9}{5 n+9}=\frac{8+9 / n}{5+9 / n} \to \frac{8+0}{5+0}=\frac{8}{5}
$$
and
$$
\frac{2+7 / n^{2}+1 / n^{3}}{6+8 / n+3 / n^{3}} \to \frac{2+0+0}{6+0+0}=\frac{1}{3}
$$
Therefore Theorem \ref{theorem-algebra-limits} Point 2 ensures that
$$
a_{n} \to \frac{8}{5} \cdot \frac{1}{3}=\frac{8}{15} \,.
$$

:::



::: Example

**Question.** Prove that 
$$
a_n = \frac{n^{7 / 3}+2 \sqrt{n}+7}{4 n^{3 / 2}+5 n}
$$
does not converge.

**Solution.** The largest power of $n$ in the denominator is $n^{3/2}$. Hence we factor out $n^{3/2}$
\begin{align*}
a_n & = \frac{n^{7 / 3}+2 \sqrt{n}+7}{4 n^{3 / 2}+5 n} \\
    & = \frac{n^{7 / 3-3 / 2}+2 n^{1/2 - 3/2} + 7  n^{-3 / 2}}{4 + 5 n^{-3/2} } \\
    & = \frac{n^{5/6}+2 n^{- 1} + 7  n^{-3 / 2}}{4 + 5 n^{-3/2} } \\
    & = \frac{b_n}{c_n}
\end{align*}
where we set
$$
b_n := n^{5/6}+2 n^{- 1} + 7  n^{-3 / 2} \,, \quad 
c_n := 4 + 5 n^{-3/2} \,.
$$
We see that $b_n$ is unbounded while $c_n \to 4$. By the Algebra of Limits (and usual contradiction argument) we conclude that $(a_n)$ is divergent.

:::


::: {.Theorem #theorem-square-root-limit}

Let $\left(a_{n}\right)_{n \in \mathbb{N}}$ be a sequence in $\mathbb{R}$ such that 
$$
\lim_{n \to \infty} \, a_n = a \,,
$$
for some $a \in \R$. If $a_{n} \geq 0$ for all $n \in \mathbb{N}$ and $a \geq 0$, then
$$
\lim _{n \rightarrow \infty} \sqrt{a_{n}}=\sqrt{a} \,.
$$

:::



::: Example 

**Question.** Define the sequence
$$
a_n  = \sqrt{9 n^{2}+3 n+1}-3 n \,.
$$
Prove that
$$
\lim_{n \to \infty} \, a_n = \frac12 \,.
$$


**Solution.** We first rewrite
\begin{align*}
a_n & = \sqrt{9 n^{2}+3 n+1}-3 n \\
& = \frac{\left(\sqrt{9 n^{2}+3 n+1}-3 n\right)\left(\sqrt{9 n^{2}+3 n+1}+3 n\right)}{\sqrt{9 n^{2}+3 n+1}+3 n} \\
& =\frac{9 n^{2}+3 n+1-(3 n)^{2}}{\sqrt{9 n^{2}+3 n+1}+3 n} \\
& =\frac{3 n+1}{\sqrt{9 n^{2}+3 n+1}+3 n} \, .
\end{align*}
The biggest power of $n$ in the denominator is $n$. Therefore we factor out $n$:
\begin{align*}
a_n & = \sqrt{9 n^{2}+3 n+1}-3 n \\
& =\frac{3 n+1}{\sqrt{9 n^{2}+3 n+1}+3 n} \\
& =\frac{3+ \dfrac{1}{n} }{\sqrt{9+ \dfrac{3}{n} + \dfrac{1}{n^{2}}} + 3 } \,.
\end{align*}
By the Algebra of Limits we have
$$
9+ \frac{3}{n} + \frac{1}{n^{2}} \to 9 + 0 + 0 = 9 \,.
$$
Therefore we can use Theorem \ref{theorem-square-root-limit} to infer
$$
\sqrt{ 9 + \frac{3}{n} + \frac{1}{n^{2}} } \to \sqrt{9}  \,.
$$
By the Algebra of Limits we conclude:
$$
a_n = \frac{3+ \dfrac{1}{n} }{\sqrt{9+ \dfrac{3}{n}  + \dfrac{1}{n^{2}} }+ 3 }   \to  \frac{ 3 + 0 }{ \sqrt{9} + 3 } = \frac12 \,.
$$


:::


::: Example 

**Question.** Prove that the sequence
$$
a_n = \sqrt{9 n^{2}+3 n+1}-2 n
$$
does not converge.

**Solution.** We rewrite $a_n$ as
\begin{align*}
a_n & = \sqrt{9 n^{2}+3 n+1}-2 n  \\
& =\frac{  (\sqrt{9 n^{2}+3 n+1} - 2 n)  (\sqrt{9 n^{2}+3 n+1}+2 n) }{\sqrt{9 n^{2}+3 n+1}+2 n} \\
& =\frac{9 n^{2}+3 n+1-(2 n)^{2}}{\sqrt{9 n^{2}+3 n+1}+2 n} \\
& =\frac{5 n^{2}+3 n+1}{\sqrt{9 n^{2}+3 n+1}+2 n} \\
& =\frac{5 n + 3 +  \dfrac{1}{n} }{\sqrt{9+ \dfrac{3}{n}  + \dfrac{1}{ n^2 } } + 2 } \\
& = \frac{b_n}{c_n} \,,
\end{align*}
where we factored $n$, being it the largest power of $n$ in the denominator, and defined
$$
b_n : = 5 n + 3 +  \dfrac{1}{n}\,, \quad 
c_n := \sqrt{9+ \dfrac{3}{n}  + \dfrac{1}{ n^2 } } + 2 \,.
$$
Note that 
$$
9+ \dfrac{3}{n}  + \dfrac{1}{ n^2 }  \to 9
$$
by the Algebra of Limits. Therefore 
$$
\sqrt{9+ \dfrac{3}{n}  + \dfrac{1}{ n^2 }}  \to \sqrt{9} = 3 
$$
by Theorem \ref{theorem-square-root-limit}. Hence 
$$
c_n = \sqrt{9+ \dfrac{3}{n}  + \dfrac{1}{ n^2 }} + 2 \to 3 + 2 = 5  \,.
$$
The numerator 
$$
b_n = 5 n + 3 +  \dfrac{1}{n}
$$
is instead unbounded. Therefore $(a_n)$ is not convergent, by the Algebra of Limits and the usual contradiction argument.
:::







## Limit Tests


In this section we discuss a number of *Tests* to determine whether a sequence converges or not. These are known as **Limit Tests**.


### Squeeze Theorem


When a sequence $(a_n)$ oscillates, it is difficult to compute the limit. Examples of terms which produce oscillations are
$$
(-1)^n \,, \quad  \sin(n) \,, \quad \cos(n) \,. 
$$
In such instance it might be useful to compare $(a_n)$ with other sequences whose limit is known. If we can prove that $(a_n)$ is *squeezed* between two other sequences with the same limiting value, then we can show that also $(a_n)$ converges to this value.



::: Theorem 
### Squeeze theorem {#theorem-squeeze}

Let $\left(a_{n}\right), \left(b_{n}\right)$ and $\left(c_{n}\right)$ be sequences in $\R$. Suppose that
$$
b_{n} \leq a_{n} \leq c_{n} \,, \quad \forall  \, n \in \N \,,
$$
and that
$$
\lim_{n \rightarrow \infty} b_{n} = \lim_{n \rightarrow \infty} c_{n} = L \, .
$$
Then
$$
\lim_{n \rightarrow \infty} a_{n}= L \, .
$$

:::


::: Proof

Let $\e>0$. Since $b_{n} \to L$ and $c_n \to L$ , there exist $N_1, N_2 \in \N$ such that 
\begin{align*}
-\e < b_n - L < \e \,, \,\, \forall \, n \geq N_1 \,,  \\
- \e < c_n - L < \e \,, \,\, \forall \, n \geq N_2 \,. 
\end{align*}
Set
$$
N := \max\{N_1,N_2\} \,.
$$
Let $n \geq N$. Using the assumption that $b_n \leq a_{n} \leq c_{n}$, we get
$$
b_n - L  \leq a_{n} - L \leq c_{n} - L \,.
$$
In particular
$$
- \e < b_n - L  \leq a_n - L \leq b_n - L < \e \,.
$$
The above implies 
$$
- \e < a_n - L < \e  \quad \implies \quad \left|a_{n}-L\right| < \e \,.
$$

:::



::: Example 

**Question.** Prove that
$$
\lim_{n \to \infty} \, \frac{(-1)^{n}}{n} = 0 \,.
$$

**Solution.** For all $n \in \N$ we can estimate
$$
-1 \leq(-1)^{n} \leq 1 \,.
$$
Therefore
$$
\frac{-1}{n} \leq \frac{(-1)^{n}}{n} \leq \frac{1}{n} \,, \quad \forall \, n \in \N \,.
$$
Moreover
$$
\lim_{n \to \infty} \frac{-1}{n}= -1 \cdot 0=0 \,, \quad 
\lim_{n \to \infty} \frac{1}{n}=0 \,.
$$
By the Squeeze Theorem \ref{theorem-squeeze} we conclude
$$
\lim_{n \to \infty} \frac{(-1)^{n}}{n}=0 \,.
$$

:::



::: {.Example #example-squeeze}

**Question.** Prove that 
$$
\lim_{n \to \infty} \frac{\cos (3 n) + 9 n^{2}}{11 n^{2}+15 \sin (17 n)} = \frac{9}{11} \,.
$$


**Solution.** We know that 
$$
-1 \leq \cos(x) \leq 1 \,, \quad - 1 \leq \sin(x) \leq 1 \,, \quad \forall \, x \in \R \,.
$$
Therefore, for all $n \in \N$
$$
- 1 \leq \cos(3n) \leq 1 \,, \quad -1 \leq \sin(17n) \leq 1 \,.
$$
We can use the above to estimate the numerator in the given sequence:
$$
-1 + 9 n^{2} \leq \cos (3 n)+9 n^{2} \leq 1+ 9 n^{2} \,.
$${#eq-squeeze-example-1}
Concerning the denominator, we have
$$
11 n^{2}-15 \leq 11 n^{2}+15 \sin (17 n) \leq  11 n^{2} + 15
$$
and therefore
$$
\frac{1}{11 n^{2} + 15} \leq \frac{1}{11 n^{2}+15 \sin (17 n)} \leq \frac{1}{11 n^{2}-15} \,.
$${#eq-squeeze-example-2}
Putting together (@eq-squeeze-example-1)-(@eq-squeeze-example-2) we obtain 
$$
\frac{-1 + 9 n^{2}}{11 n^{2} + 15} \leq \frac{\cos (3 n)+9 n^{2}}{11 n^{2}+15 \sin (17 n)} \leq \frac{1+ 9 n^{2}}{11 n^{2}-15} \,.
$$
By the Algebra of Limits we infer
$$
\frac{-1+9 n^{2}}{11 n^{2}+15}=\frac{-\dfrac{1}{n^{2}} + 9}{11 + \dfrac{15}{n^{2}}} \to \frac{0+9}{11+0}=\frac{9}{11}
$$
and
$$
\frac{1+9 n^{2}}{11 n^{2} - 15}=\frac{ \dfrac{1}{n^{2}} + 9}{ 11 - \dfrac{15}{n^{2}}} \to \frac{0+9}{11+0}=\frac{9}{11} \,.
$$
Applying the Squeeze Theorem \ref{theorem-squeeze} we conclude
$$
\lim_{n \to \infty} \frac{\cos (3 n)+ 9 n^{2}}{11 n^{2}+15 \sin (17 n)}=\frac{9}{11} \,.
$$

:::
 
::: Warning

Suppose that the sequences $(a_n), (b_n), (c_n)$ satisfy
$$
b_n \leq a_n \leq c_n \,, \quad \forall n \in \N \,,
$$
and
$$
b_n \to L_1 \,, \quad c_n \to L_2 \,, \quad L_1 \neq L_2 \,.
$$
In general, we cannot conclude that $a_n$ converges.

:::


::: Example 

Consider the sequence
$$
a_n = \left( 1 + \frac{1}{n} \right) (-1)^n  \,.
$$
For all $n \in \N$ we can bound
$$
- 1 - \frac{1}{n} \leq \left( 1 + \frac{1}{n} \right) (-1)^n   \leq 1 + \frac{1}{n}  \,.
$$
However 
$$
- 1 - \frac{1}{n} \longrightarrow - 1 - 0 = -1 
$$
and
$$
1 + \frac{1}{n}  \longrightarrow  1 + 0 = 1 \,.
$$
Since 
$$
- 1 \neq 1 \,,
$$
we cannot apply the Squeeze Theorem \ref{theorem-squeeze} to conclude convergence of $(a_n)$. Indeed, $(a_n)$ is a divergent sequence.

*Proof.* Suppose by contradiction that $a_n \to a$. We have
$$
a_n = (-1)^n + \frac{(-1)^n}{n} = b_n + c_n
$$
where
$$
b_n := (-1)^n \,, \quad c_n := \frac{(-1)^n}{n} \,.
$$
We have seen in Example \ref{example-squeeze} that $c_n \to 0$. Therefore, 
by the Algebra of Limits, we have
$$
b_n = a_n - c_n \longrightarrow a - 0 = a \,.
$$
However, Theorem \ref{theorem-1-minus-n} says that the sequence
$b_n = (-1)^n$ diverges. Contradiction. Hence $(a_n)$ diverges.

:::





### Geometric sequences


::: Definition 

A sequence $\left(a_{n}\right)$ is called a **geometric sequence** if
$$
a_{n}=x^{n} \,,
$$
for some $x \in \R$.

:::


The value of $|x|$ determines whether or not a geometric sequence converges, as shown in the following theorem.


::: Theorem 
### Geometric Sequence Test   {#theorem-geometric-sequence}

Let $x \in \R$ and let $\left(a_{n}\right)$ be the sequence defined by
$$
a_{n}:=x^{n} \,.
$$
We have:

1. If $|x|<1$, then 
$$
\lim_{n \to \infty} a_{n} = 0 \,.
$$

2. If $|x|>1$, then sequence $\left(a_{n}\right)$ is unbounded, and hence divergent.

:::



::: Warning

The Geometric Sequence Test in Theorem \ref{theorem-geometric-sequence} does not address the case
$$
|x|=1 \,.
$$
This is because, in this case, the sequence 
$$
a_n = x^n 
$$
might converge or diverge, depending on the value of $x$. Indeed, 
$$
|x| = 1 \quad \implies \quad x = \pm 1 \,.
$$
We therefore have two cases:

- $x = 1$: Then 
$$
a_n = 1^n = 1
$$
so that $a_n \to 1$ and $(a_n)$ is convergent.

- $x=-1$: Then
$$
a_n = x^n = (-1)^n
$$
which is divergent by Theorem \ref{theorem-1-minus-n}.

:::



To prove Theorem \ref{theorem-geometric-sequence} we need the following inequality, known as Bernoulli's inequality.


::: Lemma 
### Bernoulli's inequality  {#lemma-bernoulli}

Let $x \in \R$ with $x>-1$. Then
$$
(1+x)^{n} \geq 1+n x \,, \quad \forall \, n \in \N \,.
$${#eq-bernoulli-inequality}

:::


::: Proof

Let $x \in \mathbb{R}, x>-1$. We prove the statement by induction:

- Base case: (@eq-bernoulli-inequality) holds with equality when $n=1$.

- Induction hypothesis: Let $k \in \N$ and suppose that (@eq-bernoulli-inequality) holds for $n=k$, i.e.,
$$
(1+x)^{k} \geq 1+k x \,.
$$
Then
\begin{align*}
(1+x)^{k+1} & = (1+x)^{k}(1+x) \\
            & \geq(1+k x)(1+x) \\
            & =1+k x+x+k x^{2} \\
            & \geq 1+(k+1) x \,,
\end{align*}
where we used that $kx^2 \geq 0$. Then (@eq-bernoulli-inequality) holds for $n=k+1$.

By induction we conclude (@eq-bernoulli-inequality).

:::


We are ready to prove Theorem \ref{theorem-geometric-sequence}.


::: Proof 
### Proof of Theorem \ref{theorem-geometric-sequence}

*Part 1. The case $|x|<1$*. 

If $x=0$, then
$$
a_n = x^n = 0 
$$
so that $a_n \to 0$. Hence assume $x \neq 0$. We need to prove that
$$
\forall \, \e> 0 \,, \, \exists \, N \in \N \st 
\forall \, n \geq N \,, \,\, |x^n - 0| < \e \,.
$$
Let $\e>0$. We have 
$$
|x| < 1 \quad \implies \quad \frac{1}{|x|} > 1 \,.
$$
Therefore 
$$
|x|= \frac{1}{1+u} \,, \quad u:=\frac{1}{|x|} - 1 > 0 \,.
$$
Let $N \in \N$ be such that 
$$
N > \frac{1}{\e u} \,,
$$
so that 
$$
\frac{1}{N u} < \e \,.
$$
Let $n \geq N$. Then
\begin{align*}
\left|x^{n}-0\right| & =|x|^{n} \\
                     & = \left(\frac{1}{1+u}\right)^{n} \\
                     & =\frac{1}{(1+u)^{n}} \\
                     & \leq \frac{1}{1+n u} \\
                     & \leq \frac{1}{n u} \\
                     & \leq \frac{1}{N u} \\
                     & < \e \,,
\end{align*}
where we used Bernoulli's inequality (@eq-bernoulli-inequality) in the first inequality.


*Part 2. The case $|x|>1$*. 

To prove that $(a_n)$ does not converge, we prove that it is unbounded. 
This means showing that
$$
\forall \, M > 0 \,, \, \exists n \in \N \st  \left| a_{n}\right| >M \,.
$$
Let $M > 0$. We have two cases: 

- $0 < M \leq 1$: Choose $n=1$. Then
$$
\left|a_{1}\right|=|x|>1 \geq M \,.
$$

- $M>1$: Choose $n \in \N$ such that 
$$
n> \frac{\log M}{\log |x|} \,.
$$ 
Note that $\log |x|>0$ since $|x|>1$. Therefore
\begin{align*}
n>\frac{\log M}{\log |x|} & \iff n \log |x|>\log M \\
                          & \iff \log |x|^n>\log M \\
                          & \iff |x|^{n}>M \,.
\end{align*}
Then 
$$
\left|a_{n}\right|=\left|x^{n}\right|=|x|^{n} > M \,.
$$


Hence $(a_n)$ is unbounded. By Corollary \ref{corollary-convergent-bounded} we conclude that $(a_n)$ is divergent. 


:::






::: Example 

We can apply Theorem \ref{theorem-geometric-sequence} to prove convergence
or divergence for the following sequences.

1. We have
$$
\left(\frac{1}{2}\right)^{n} \longrightarrow 0
$$
since 
$$
\left|\frac{1}{2}\right|=\frac{1}{2}<1 \,.
$$

2. We have
$$
\left(\frac{-1}{2}\right)^{n} \longrightarrow 0
$$
since 
$$
\left|\frac{-1}{2}\right|=\frac{1}{2}<1 \,.
$$

3. The sequence 
$$
a_n = \left(\frac{-3}{2}\right)^{n}
$$ 
does not converge, since 
$$
\left|\frac{-3}{2}\right|=\frac{3}{2}>1 \,.
$$

4. As $n \rightarrow \infty$,
$$
\frac{3^{n}}{(-5)^{n}}=\left(-\frac{3}{5}\right)^{n} \longrightarrow 0
$$
since 
$$
\left|-\frac{3}{5}\right|=\frac{3}{5}<1 \,.
$$

5. The sequence 
$$
a_{n}=\frac{(-7)^{n}}{2^{2 n}}
$$ 
does not converge, since
$$
\frac{(-7)^{n}}{2^{2 n}}=\frac{(-7)^{n}}{\left(2^{2}\right)^{n}}=\left(-\frac{7}{4}\right)^{n}
$$
and 
$$
\left|-\frac{7}{4}\right|=\frac{7}{4}>1  \,.
$$

:::







### Ratio Test



::: Theorem 
### Ratio Test {#theorem-ratio-test}

Let $\left(a_{n}\right)$ be a sequence in $\R$ such that
$$
a_{n} \neq 0 \,, \quad \forall \, n \in \N \,.
$$ 


1. Suppose that the following limit exists:
$$
L:=\lim_{n \to \infty}\left|\frac{a_{n+1}}{a_{n}}\right| \,.
$$
Then,

    - If $L<1$ we have
    $$
    \lim_{n \to\infty} a_{n}=0 \,.
    $$

    - If $L>1$, the sequence $\left(a_{n}\right)$ is unbounded, and hence does not converge.

2. Suppose that there exists $N \in \N$ and $L>1$ such that
$$
\left|\frac{a_{n+1}}{a_{n}}\right| \geq L \,, \quad \forall \, n \geq N \,. 
$$
Then the sequence $\left(a_{n}\right)$ is unbounded, and hence does not converge.

:::



::: Proof

Define the sequence $b_{n}=\left|a_{n}\right|$. Then,

$$
\left|\frac{a_{n+1}}{a_{n}}\right|=\frac{\left|a_{n+1}\right|}{\left|a_{n}\right|}=\frac{b_{n+1}}{b_{n}}
$$


*Part 1.* Suppose that there exists the limit
$$
L:=\lim_{n \to \infty}\left|\frac{a_{n+1}}{a_{n}}\right| \,.
$$
Therefore 
$$
\lim_{n \to \infty} \frac{b_{n+1}}{b_{n}} = L \,.
$${#eq-ratio-test-proof}

- $L<1$: Choose $r>0$ such that 
$$
L<r<1 \,.
$$
Set 
$$
\e := r-L
$$
By the convergence at (@eq-ratio-test-proof) there exists $N \in \N$ such that
$$
\left|\frac{b_{n+1}}{b_{n}}-L\right| < \e = r - L \,, \quad \forall \, n \geq N \,.
$$
In particular 
$$
\frac{b_{n+1}}{b_{n}}-L < r-L \,, \quad \forall \, n \geq N \,,
$$
which implies 
$$
b_{n+1} <  r \,{b_{n}} \,, \quad \forall \, n \geq N \,.
$${#eq-ratio-test-proof-1}
Let $n \geq N$, we can use (@eq-ratio-test-proof-1) recursively and obtain
$$
0 \leq b_{n} < \, r b_{n-1} < \ldots < r^{n-N} \, b_{N} = r^{n} \, \frac{b_{N}}{r^{N}} \,.
$$
In particular, we have proven that
$$
0 \leq b_{n} < r^{n} \, \frac{b_{N}}{r^{N}} \,, \quad \forall \, n \in \N \,.
$${#eq-ratio-test-proof-2}
Since $|r|<1$, by the Geometric Sequence Test Theorem \ref{theorem-geometric-sequence} we infer
$$
r^{n} \rightarrow 0 \,.
$$
The Algebra of Limits the yields
$$
r^{n} \, \frac{b_{N}}{r^{N}} \rightarrow 0 \,.
$$
By the Squeeze Theorem \ref{theorem-squeeze} applied to (@eq-ratio-test-proof-2), it follows that 
$$   
b_{n} = |a_n| \to 0 \,.
$$
Since 
$$
-\left|a_{n}\right| \leq a_{n} \leq\left|a_{n}\right| \,,
$$
and 
$$
-|a_n| \to 0 \,, \quad |a_n| \to 0 \,, 
$$
we can again apply the Squeeze Theorem \ref{theorem-squeeze} to infer
$$
a_{n} \rightarrow 0 \,.
$$


- $L>1$: Choose $r>0$ such that 
$$
1<r<L  \,.
$$
Define
$$
\e := L - r > 0 \,.
$$
By the convergence (@eq-ratio-test-proof), there exists $N \in \N$ such that
$$
\left|\frac{b_{n+1}}{b_{n}}-L\right| < \e = L - r \,, \quad \forall \, n \geq N \,.
$$
In particular,
$$
-(L-r) < \frac{b_{n+1}}{b_{n}}-L \,, \quad \forall \, n \geq N \,,
$$
which implies
$$
b_{n+1} > r \, b_{n} \,, \quad  \forall \, n \geq N \,.
$${#eq-ratio-test-proof-4}
Let $n \geq N$. Applying (@eq-ratio-test-proof-4) recursively we get
$$
b_{n} > r^{n-N} \, b_{N} = r^{n} \, \frac{b_{N}}{r^{N}} \,, \quad \forall \, n \geq N \,.
$${#eq-ratio-test-proof-5}
Since $|r|>1$, by the Geometric Sequence Test we have that the sequence
$$
(r^n)
$$
is unbounded. Therefore also the right hand side of (@eq-ratio-test-proof-5) is unbounded, proving that $(b_n)$ is unbounded. Since
$$
b_n = |a_n|\,,
$$
we conclude that $(a_n)$ is unbounded. By Corollary \ref{corollary-convergent-bounded} we conclude that $(a_n)$ does not converge.


*Part 2.* Suppose that there exists $N \in \N$ and $L>1$ such that
$$
\left|\frac{a_{n+1}}{a_{n}}\right| \geq L \,, \quad \forall \, n \geq N \,. 
$$
Since $b_n = |a_n|$, we infer
$$
b_{n+1} \geq L \, b_n \,, \quad \forall \, n \geq N \,. 
$$
Arguing as above, we obtain
$$
b_n \geq L^n \, \frac{b_N}{L^N} \,, \quad \forall \, n \geq N \,.
$$
Since $L>1$, we have that the sequence 
$$  
L^n \, \frac{b_N}{L^N}
$$
is unbounded, by the Geometric Sequence Test. Hence also $(b_n)$ is unbounded, from which we conclude that $(a_n)$ is unbounded. By Corollary \ref{corollary-convergent-bounded} we conclude that $(a_n)$ does not converge.


:::


Let us apply the Ratio Test to some concrete examples.



::: Example

**Question.** Let 
$$
a_{n}=\frac{3^{n}}{n !} \,,
$$
where we recall that $n!$ (pronounced $n$ factorial) is defined by
$$
n! := n \cdot (n-1) \cdot (n-2) \cdot  \ldots \cdot  3 \cdot 2 \cdot 1 \,. 
$$
Prove that
$$
\lim_{n \to \infty} a_n  = 0 \,.
$$

**Solution.** We have
\begin{align*}
\left|\frac{a_{n+1}}{a_{n}}\right| & = \dfrac{\left( \dfrac{3^{n+1}}{(n+1) !} \right) }{  \left( \dfrac{3^{n}}{n !} \right) } \\
& = \frac{3^{n+1}}{3^{n}} \, \frac{n !}{(n+1) !} \\
& = \frac{3 \cdot 3^n}{3^n} \, \frac{n!}{(n+1) n!} \\
& =\frac{3}{n+1} \longrightarrow L = 0 \,.
\end{align*}
Hence, $L=0<1$ so $a_{n} \to 0$ by the Ratio Test in Theorem \ref{theorem-ratio-test}.

:::


::: Example

**Question.** Consider the sequence
$$
a_{n}=\frac{n ! \cdot 3^{n}}{\sqrt{(2 n) !}} \,.
$$
Prove that $(a_n)$ is divergent.

**Solution.** We have
\begin{align*}
\left|\frac{a_{n+1}}{a_{n}}\right| & =\frac{(n+1) ! \cdot 3^{n+1}}{\sqrt{(2(n+1)) !}}  \frac{\sqrt{(2 n) !}}{n ! \cdot 3^{n}} \\
& =\frac{(n+1) !}{n !} \cdot \frac{3^{n+1}}{3^{n}} \cdot \frac{\sqrt{(2 n) !}}{\sqrt{(2(n+1)) !}}
\end{align*}
For the first two fractions we have
$$
\frac{(n+1) !}{n !} \cdot \frac{3^{n+1}}{3^{n}} = 3(n+1) \,,
$$
while for the third fraction
\begin{align*}
\frac{\sqrt{(2 n) !}}{\sqrt{(2(n+1)) !}} & =\sqrt{\frac{(2 n) !}{(2 n+2) !}} \\
& = \sqrt{\frac{ (2n)! }{ (2n+2) \cdot (2n+1) \cdot (2n)! }} \\
& = \frac{1}{\sqrt{(2 n+1)(2 n+2)}} \,.
\end{align*}
Therefore, using the Algebra of Limits,
\begin{align*}
\left|\frac{a_{n+1}}{a_{n}}\right| & = \frac{3(n+1)}{\sqrt{(2 n+1)(2 n+2)}}\\
& = \frac{3n \left(1+ \dfrac{1}{n} \right)}{\sqrt{n^2 \left( 2 + \dfrac{1}{n}\right) \left(2 + \dfrac{2}{n} \right)}} \\
& = \frac{3 \left(1+ \dfrac{1}{n} \right)}{\sqrt{ \left( 2 + \dfrac{1}{n}\right) \left(2 + \dfrac{2}{n} \right)}}  \longrightarrow \frac{3}{\sqrt{4}} = \frac{3}{2} > 1 \,.
\end{align*}
By the Ratio Test we conclude that $(a_n)$ is divergent.

:::



::: Example 

**Question.** Prove that the following sequence is divergent
$$
a_{n}=\frac{n !}{100^{n}} \,.
$$


**Solution.** We have
$$
\left|\frac{a_{n+1}}{a_{n}}\right| 
= \frac{100^{n}}{100^{n+1}} \frac{(n+1) !}{n !}
=\frac{n+1}{100} \,.
$$
Choose $N=101$. Then for all $n \geq N$,
\begin{align*}
\left|\frac{a_{n+1}}{a_{n}}\right| 
& = \frac{n+1}{100} \\
& \geq \frac{N+1}{100} \\
& = \frac{101}{100} > 1 \,.
\end{align*}
Hence $a_{n}$ is divergent by the Ratio Test.

:::




::: Warning

The Ratio Test in Theorem \ref{theorem-ratio-test} does not address the case
$$
L=1 \,.
$$
This is because, in this case, the sequence $(a_n)$ 
might converge or diverge. 

For example:

- Define the sequence
$$
a_n = \frac1n \,.
$$
We have
$$
\left|\frac{a_{n+1}}{a_{n}}\right| = \frac{n}{n+1} \rightarrow L = 1 \,. 
$$
Hence we cannot apply the Ratio Test. However we know that 
$$
\lim_{n \to \infty} \, \frac1n = 0 \,.
$$


- Consider the sequence
$$
a_n = n \,.
$$
We have
$$
\frac{|a_{n+1}|}{|a_n|} = \frac{n+1}{n} \rightarrow L = 1 \,. 
$$
Hence we cannot apply the Ratio Test. However we know that $(a_n)$ is unbounded, and thus divergent.

:::



If the sequence $(a_n)$ is geometric, the Ratio Test of Theorem \ref{theorem-ratio-test} will give the same
answer as the Geometric Sequence Test of Theorem \ref{theorem-geometric-sequence}. This is the content of the following remark.


::: Remark

Let $x \in \R$ and define the geometric sequence 
$$
a_{n}=x^{n} \,.
$$
Then
$$
\left|\frac{a_{n+1}}{a_{n}}\right|  = \frac{\left|x^{n+1}\right|}{\left|x^{n}\right|} 
= \frac{|x|^{n+1}}{|x|^{n}} 
 =|x| \rightarrow |x| \,.
$$
Hence: 

- If $|x|<1$, the sequence $(a_n)$ converges by the Ratio Test
- If $|x|>1$, the sequence $(a_n)$ diverges by the Ratio Test. 
- If $|x|=1$, the sequence $(a_n)$ might be convergent or divergent.

These results are in agreement with the Geometric Sequence Test. 

:::






## Monotone sequences


We have seen in Theorem \ref{theorem-convergent-bounded} that convergent sequences are bounded. We noted that the converse statement is not true. 
For example the sequence
$$
a_n = (-1)^n
$$
is bounded but not convergent, as shown in Theorem \ref{theorem-1-minus-n}.
On the other hand, if a bounded sequence is **monotone**, then it is convergent.


::: Definition
### Monotone sequence

Let $(a_n)$ be a real sequence. We say that:

1. $(a_n)$ is **increasing** if 
$$
a_n \leq a_{n+1} \,, \quad \forall \, n \geq N \,.
$$

2. $(a_n)$ is **decreasing** if 
$$
a_n \geq a_{n+1} \,, \quad \forall \, n \geq N \,.
$$

3. $(a_n)$ is **monotone** if it is either increasing or decreasing.

:::



::: Example

**Question.** Prove that the following sequence is increasing
$$
a_n = \frac{n-1}{n} \,.
$$

**Solution.** We have
$$
a_{n+1} = \frac{n}{n+1} > \frac{n-1}{n} = a_n \,,
$$
where the inequality holds because
\begin{align*}
\frac{n}{n+1} > \frac{n-1}{n} \quad & \iff \quad 
n^2 > (n-1)(n+1) \quad  \\
& \iff \quad n^2 > n^2 - 1 \\
& \iff \quad 0 >  - 1
\end{align*}
:::


::: Example
 
**Question.** Prove that the following sequence is decreasing
$$
a_n = \frac1n \,.
$$

**Solution.** We have
$$
a_n = \frac1n > \frac{1}{n+1} = a_{n+1} \,,
$$
concluding.

:::



The main result about monotone sequences is the Monotone Convergence
Theorem.


::: Theorem
### Monotone Convergence Theorem  {#theorem-monotone-convergence}

Let $(a_n)$ be a sequence in $\R$. Suppose that $(a_n)$ is bounded and
monotone. Then $(a_n)$ converges.

:::


::: Proof

Assume $(a_n)$ is bounded and monotone. Since $(a_n)$ is bounded, the set 
$$
A:=\{ a_n \divider n \in \N \}  \subseteq \R 
$$
is bounded below and above. By the Axiom of Completeness of $\R$ there exist $i,s \in \R$ such that
$$
i = \inf A \,, \quad s = \sup A \,.
$$

We have two cases:

1. $(a_n)$ is increasing: We are going to prove that
$$
\lim_{n \to \infty} a_n = s \,.
$$
Equivalently, we need to prove that
$$
\forall \, \e>0 \,, \, \exists \, N \in \N \st \forall \, n \geq N \,, \,\,
|a_n - s| < \e \,. 
$${#eq-monotone-conv-proof}
Let $\e > 0$. Since $s$ is the smallest upper bound for $A$, this means
$$
s - \e
$$
is not an upper bound. Therefore there exists $N \in \N$ such that 
$$
s - \e < a_N \,.
$${#eq-monotone-convergence-proof-1}
Let $n \geq N$. Since $a_n$ is increasing, we have
$$
a_N \leq a_n \,, \quad \forall \, n \geq N \,.
$${#eq-monotone-convergence-proof-2}
Moreover $s$ is the supremum of $A$, so that
$$
a_n \leq s < s + \e \,, \quad \forall \, n \in \N \,.
$${#eq-monotone-convergence-proof-3}
Putting together estimates (@eq-monotone-convergence-proof-1)-(@eq-monotone-convergence-proof-2)-(@eq-monotone-convergence-proof-3)
we get
$$
s - \e < a_N \leq a_n \leq s < s + \e \,, \quad \forall \, n \geq N \,.
$$
The above implies 
$$
s - \e < a_n < s + \e \,, \quad \forall \, n \geq N \,,
$$
which is equivalent to (@eq-monotone-conv-proof).




2. $(a_n)$ is decreasing: With a similar proof, one can show that
$$
\lim_{n \to \infty} a_n = i \,.
$$
This is left as an exercise.


:::








### Example: Euler's Number


As an application of the Monotone Convergence Theorem we can give
a formal definition for the Euler's Number
$$
e = 2.71828182845904523536 \dots
$$


::: {.Theorem #theorem-euler-number}

Consider the sequence
$$
a_n = \left(  1 + \frac{1}{n}  \right)^n  \,.
$$

We have that:

1. $(a_n)$ is monotone increasing,
2. $(a_n)$ is bounded.

In particular $(a_n)$ is convergent.

:::



::: Proof


*Part 1.* We prove that $(a_n)$ is increasing
$$
a_{n} \geq a_{n-1} \,, \quad \forall \, n \in \N \,,
$$
which by definition is equivalent to
$$
\left(  1 + \frac{1}{n}  \right)^n \geq 
\left(  1 + \frac{1}{n - 1}  \right)^{n-1} \,, \quad \forall \, n \in \N \,.
$$
Summing the fractions we get
$$
\left(  \frac{n+1}{n}  \right)^n \geq 
\left(  \frac{n}{n-1}  \right)^{n-1} \,.  
$$
Multiplying by $((n-1)/n)^n$ we obtain
$$
\left(  \frac{n-1}{n}  \right)^n  \left(  \frac{n+1}{n}  \right)^n  \geq 
 \frac{n-1}{n}  \,,
$$
which simplifies to
$$
\left(  1 - \frac{1}{n^2}  \right)^n \geq 1 - \frac1n \,, \quad  \forall \, n \in \N \,.
$${#eq-proof-euler-1}
Therefore $(a_n)$ is increasing if and only if (@eq-proof-euler-1) holds.
Recall Bernoulli's inequality from Lemma \ref{lemma-bernoulli}: For
$x \in \R$, $x>-1$, it holds
$$
(1 + x )^n  \geq 1 + nx  \,, \quad \forall \, n \in \N \,.
$$
Appliying Bernoulli's inequality with 
$$
x = -\frac{1}{n^2}
$$
yields
$$
\left(  1 - \frac{1}{n^2}  \right)^n  \geq 1 + n \left( -\frac{1}{n^2} \right) = 1 - \frac{1}{n} \,,
$$
which is exactly (@eq-proof-euler-1). Then $(a_n)$ is increasing.



*Part 2*. We have to prove that $(a_n)$ is bounded, that is, that there
exists $M > 0$ such that
$$
|a_n| \leq M \,, \quad \forall \, n \in \N \,.
$$
To this end, introduce the sequence $(b_n)$ by setting
$$
b_n := \left(   1  + \frac1n \right)^{n+1} \,.
$$
The sequence $(b_n)$ is decreasing.

> To prove $(b_n)$ is decreasing, we need to show that 
$$
b_{n-1} \geq b_n \,, \quad \forall \, n \in \N \,. 
$$
By definition of $b_n$, the above reads
$$
\left(   1  + \frac{1}{n-1} \right)^{n} \geq
\left(   1  + \frac{1}{n} \right)^{n+1} \,, \quad \forall \, n \in \N \,.
$$
Summing the terms inside the brackets, the above is equivalent to
$$
\left(   \frac{n}{n-1} \right)^{n} \geq
\left(   \frac{n+1}{n} \right)^{n} \left(   \frac{n+1}{n} \right) \,.
$$
Multiplying  by $(n/(n+1))^n$ we get
$$
\left(  \frac{n^2}{n^2 - 1} \right)^{n} \geq  \left(   \frac{n+1}{n} \right) \,.
$$
The above is equivalent to
$$
\left( 1 +  \frac{1}{n^2 - 1} \right)^{n} \geq  \left(  1 + \frac{1}{n} \right) \,.
$${#eq-proof-euler-3}
Therefore $(b_n)$ is decreasing if and only if (@eq-proof-euler-3) holds for all $n \in \N$.
By choosing 
$$
x = \frac{1}{n^2 - 1} 
$$
in Bernoulli's inequality, we obtain
\begin{align*}
\left( 1 +  \frac{1}{n^2 - 1} \right)^{n} & \geq 1 + n \left(  \frac{1}{n^2 - 1}   \right) \\
& = 1 + \frac{n}{n^2 - 1} \\
& \geq 1 + \frac1n \,,
\end{align*}
where in the last inequality we used that 
$$
 \frac{n}{n^2 - 1} > \frac1n \,,
$$
which holds, being equivalent to $n^2 > n^2 - 1$. We have therefore proven
(@eq-proof-euler-3), and hence $(b_n)$ is decreasing.


We now observe that
For all $n \in \N$
\begin{align*}
b_n & = \left(   1  + \frac1n \right)^{n+1} \\
    & = \left(   1  + \frac1n \right)^n \left(   1  + \frac1n \right) \\ 
    & = a_n \left(   1  + \frac1n \right) \\
    & > a_n \,.
\end{align*}
Since $(a_n)$ is increasing and $(b_n)$ is decreasing, in particular
$$
a_n \geq a_1 \,, \quad b_n \leq b_1 \,.
$$
Therefore
$$
a_1 \leq a_n < b_n \leq b_1 \,, \quad \forall \, n \in \N \,.
$$
We compute
$$
a_1 = 2 \,, \quad b_1 = 4 \,,
$$
from which we get 
$$
2 \leq a_n \leq 4 \,, \quad \forall \, n \in \N \,.
$$
Therefore 
$$
|a_n| \leq 4 \,, \quad \forall \, n \in \N \,,
$$
showing that $(a_n)$ is bounded.


*Part 3.* The sequence $(a_n)$ is increasing and bounded above. Therefore $(a_n)$ is convergent by the Monotone Convergence Theorem \ref{theorem-monotone-convergence}.

:::




Thanks to Theorem \ref{theorem-euler-number} we can define the Euler's Number $e$.


::: Definition
### Euler's Number

The Euler's number is defined as
$$
e := \lim_{n \to \infty } \, \left(  1 + \frac{1}{n}  \right)^n \,.
$$

:::


Setting $n=1000$ in the formula for $(a_n)$, we get an approximation of $e$:
$$
e \approx a_{1000} = 2.7169 \,.
$$






## Some important limits



In this section we investigate limits of some sequences to which 
the Limit Tests do not apply.


::: Theorem

Let $x \in \R$, with $x > 0$. Then
$$
\lim_{n \to \infty} \sqrt[n]{x} = 1 \,.
$$

:::


::: Proof

*Step 1.* Assume $x \geq 1$. In this case
$$
\sqrt[n]{x} \geq 1 \,.
$$
Define 
$$
b_n := \sqrt[n]{x} - 1 \,,
$$
so that $b_n \geq 0$. By Bernoulli's Inequality we have
$$
x = (1 + b_n)^n \geq 1 + n b_n \,.
$$
Therefore 
$$
0 \leq b_n \leq \frac{x-1}{n} \,.
$$
Since 
$$
\frac{x-1}{n} \longrightarrow 0 \,,
$$
by the Squeeze Theorem we infer $b_n \to 0$, and hence 
$$
\sqrt[n]{x} = 1 + b_n \longrightarrow 1 + 0 = 1\,, 
$$
by the Algebra of Limits.

*Step 2.* Assume $0< x < 1$. In this case
$$
\frac{1}{x} > 1 \,.
$$
Therefore
$$
\lim_{n \to \infty} \, \sqrt[n]{  1/x  } = 1  \,.
$$
by Step 1. Therefore
$$
\sqrt[n]{x} = \frac{1}{\sqrt[n]{  1/x  }} \longrightarrow \frac{1}{1} = 1\,,
$$
by the Algebra of Limits.

:::



::: {.Theorem   #theorem-important-limit-1}

Let $(a_n)$ be a sequence such that $a_n \to 0$. Then
$$
\sin(a_n) \to 0 \,, \quad 
\cos(a_n) \to 1 \,.
$$

:::

::: Proof

Assume that $a_n \to 0$ and set
$$
\e := \frac{\pi}{2} \,.
$$
By the convergence $a_m \to 0$ there exists $N \in \N$ such that
$$
|a_n| < \e = \frac{\pi}{2} \, \quad \forall \, n \geq N \,.
$${#eq-limiti-notevoli-1}


*Step 1*. We prove that 
$$
\sin(a_n) \to 0 \,.
$$
By elementary trigonometry we have
$$
0 \leq |\sin (x)| = \sin |x| \leq |x| \,, \quad \forall  \, x \in \left[
-\frac{\pi}{2}, \frac{\pi}{2} \right] \,.
$$
Therefore, since (@eq-limiti-notevoli-1) holds, we can substitute $x=a_n$ in the above inequality to get
$$
0 \leq |\sin (a_n)|  \leq |a_n| \,, \quad \forall \, n \geq \N \,.
$$
Since $a_n \to 0$, we also have $|a_n|\to 0$. Therefore 
$|\sin (a_n)| \to 0$ by the Squeeze Theorem. This immediately implies 
$\sin(a_n) \to 0$.

*Step 2*. We prove that 
$$
\cos(a_n) \to 1 \,.
$$
Inverting the relation
$$
\cos^2(x) + \sin^2 (x) = 1 \,,
$$
we obtain
$$
\cos(x) = \pm \sqrt{ 1 - \sin^2 (x) } \,.
$$
We have that $\cos(x) \geq 0$ for $-\pi/2 \leq x \leq \pi/2$. Thus
$$
\cos(x) = \sqrt{ 1 - \sin^2 (x) } \,, \quad \forall \, x \in 
\left[ -\frac{\pi}{2}, \frac{\pi}{2} \right] \,.
$$
Since (@eq-limiti-notevoli-1) holds, we can set $x=a_n$ in the above inequality and obtain
$$
\cos(a_n) = \sqrt{ 1 - \sin^2 (a_n) } \,, \quad \forall \, n \geq N \,. 
$$
By Step 1 we know that $\sin(a_n) \to 0$. Therefore, by the Algebra of Limits,
$$
 1 - \sin^2 (a_n) \longrightarrow 1 - 0 \cdot 0 = 1 \,.
$$
Using Theorem \ref{theorem-square-root-limit} we have
$$
\cos(a_n) = \sqrt{1 - \sin^2 (a_n)} \longrightarrow \sqrt{1} = 1 \,,
$$
concluding the proof.


:::



::: {.Theorem  #theorem-important-limit-2}

Suppose $(a_n)$ is such that $a_n \to 0$ and 
$$
a_n \neq 0 \,, \quad \forall \, n \in \N \, .
$$
Then
$$
\lim_{n \to \infty} \frac{\sin(a_n)}{a_n} = 1 \,.
$$

:::


::: Proof

The following elementary trigonometric inequality holds:
$$
\sin (x) < x < \tan (x) \,, \quad \forall \, x \in \left[0 ,\frac{\pi}{2} \right]  \,.
$$
Note that $\sin x >0$ for $0 < x < \pi/2$. Therefore we can divide the
above inequality by $\sin(x)$ and take the reciprocals to get
$$
\cos(x) < \frac{\sin (x)}{x} < 1 \,, \quad \forall \, x \in \Big( 0 ,\frac{\pi}{2} \Big] \,.
$$
If $-\pi/2<x<0$, we can apply the above inequality to $-x$ to obtain
$$
\cos(-x) < \frac{\sin(-x)}{-x} < 1  \,.
$$
Recalling that $\cos(-x) = \cos(x)$ and $\sin(-x)=-\sin(x)$, we get
$$
\cos(x) < \frac{\sin(x)}{x} < 1  \,, \quad \forall \, x \in \Big( -\frac{\pi}{2}, 0 \Big] \,.
$$
Thus
$$
\cos(x) < \frac{\sin(x)}{x} < 1  \,, \quad \forall  \, x \in \left[-\frac{\pi}{2}, \frac{\pi}{2} \right] \smallsetminus \{0\} \,.
$${#eq-limiti-notevoli-3}
Let 
$$
\e := \frac{\pi}{2} \,.
$$
Since $a_n \to 0$, there exists $N \in \N$ such that
$$
|a_n| < \e = \frac{\pi}{2} \,, \quad \forall \, n \geq N \,.
$$
Since $a_n \neq 0$ by assumption, the above shows that
$$
a_n \in \Big[ -\frac{\pi}{2}, \frac{\pi}{2}  \Big] \smallsetminus \{0\} \,, 
\quad \forall \, n \geq \N \,.
$$
Therefore we can substitute $x=a_n$ into (@eq-limiti-notevoli-3) to get
$$
\cos(a_n) < \frac{\sin(a_n)}{a_n} < 1  \,, \quad \forall  \, n \geq N \,.
$$
We have
$$
\cos(a_n) \to 1
$$ 
by Theorem \ref{theorem-important-limit-1}. By the Squeeze Theorem we conclude that
$$
\lim_{n \to \infty} \frac{\sin(a_n)}{a_n} = 1 \,.
$$

:::



::: Warning

You might be tempted to apply L'Hpital's rule (which we did not cover in these Lecture Notes) to compute 
$$
\lim_{x \to 0} \frac{\sin(x)}{x}  \,.
$$
This would yield the correct limit
$$
\lim_{x \to 0} \frac{\sin(x)}{x} =
\lim_{x \to 0} \frac{(\sin(x))'}{(x)'} = 
\lim_{x \to 0} \cos(x) = 1  \,.
$$
However this is a circular argument, since the derivative of 
$\sin(x)$ at $x=0$ is defined as the limit
$$
\lim_{x \to 0} \frac{\sin(x)}{x} \,.
$$

:::




::: {.Theorem  #theorem-important-limit-3}

Suppose $(a_n)$ is such that $a_n \to 0$ and 
$$
a_n \neq 0 \,, \quad \forall \, n \in \N \, .
$$
Then
$$
\lim_{n \to \infty} \frac{1 - \cos(a_n)}{(a_n)^2} = \frac{1}{2} \,, \quad 
\lim_{n \to \infty} \frac{1 - \cos(a_n)}{a_n} = 0  \, .
$$

:::


::: Proof

*Step 1.*  By Theorem \ref{theorem-important-limit-1} and Theorem \ref{theorem-important-limit-2}, we have
$$
\cos(a_n) \to 1 \,, \quad \frac{\sin(a_n)}{a_n} \to 1 \,.
$$
Therefore
\begin{align*}
\frac{1 - \cos(a_n)}{(a_n)^2} & = 
\frac{1 - \cos(a_n)}{(a_n)^2} \, \frac{1 + \cos(a_n)}{1 + \cos(a_n)} \\
& = \frac{1 - \cos^2(a_n)}{(a_n)^2} \,  \frac{1}{1 + \cos(a_n)} \\
& = \left( \frac{\sin(a_n)}{a_n}   \right)^2 \, \frac{1}{1 + \cos(a_n)} \longrightarrow 1 \cdot \frac{1}{1 + 1} = \frac12 \,,
\end{align*}
where in the last line we use the Algebra of Limits. 

*Step 2.* We have
$$
\frac{1 - \cos(a_n)}{a_n} =  a_n \cdot \frac{1 - \cos(a_n)}{(a_n)^2} \longrightarrow 0 \cdot \frac{1}{2} = 0 \,, 
$$
using Step 1 and the Algebra of Limits.



:::





::: Example

**Question.** Prove that
$$
\lim_{n \to \infty} \, n  \sin \left(  \frac{1}{n} \right)  = 1 \,.
$${#eq-notable-limits-2}

**Solution.** This is because
$$
n  \sin \left(  \frac{1}{n} \right) = \frac{ \sin \left(  \dfrac{1}{n} \right) }{ \dfrac{1}{n} } \longrightarrow 1 \,,
$$
by Theorem \ref{theorem-important-limit-2} with $a_n = 1/n$.

:::


::: Example

**Question.** Prove that
$$
\lim_{n \to \infty} \, n^2 \left(  1 - \cos \left(  \dfrac{1}{n} \right)  \right) = \frac12 \,.
$${#eq-notable-limits-1}


**Solution.** Indeed, 
$$
n^2 \left(  1 - \cos \left(  \frac{1}{n} \right)\right) = \dfrac{1 - \cos \left(  \dfrac{1}{n} \right)}{\dfrac{1}{n^2}} \longrightarrow \frac12 \,,
$$
by applying Theorem \ref{theorem-important-limit-3} with $a_n = 1/n$.

:::


::: Example

**Question.** Prove that
$$
\lim_{n \to \infty} \, \frac{n  \left( 1- \cos \left(  \dfrac{1}{n} \right) \right) }{ \sin \left( \dfrac{1}{n} \right) } = \frac12 \,.
$$

**Solution.** Using (@eq-notable-limits-1)-(@eq-notable-limits-2) and the Algebra of Limits
\begin{align*}
 \frac{n  \left( 1- \cos \left(  \dfrac{1}{n} \right) \right) }{ \sin \left( \dfrac{1}{n} \right) } & =
  \frac{n^2  \left( 1- \cos \left(  \dfrac{1}{n} \right) \right) }{ n \sin \left( \dfrac{1}{n} \right) } \\
  & \longrightarrow \frac{1/2}{1} = \frac12 \,.
\end{align*}

:::



::: Example

**Question.** Prove that
$$
\lim_{n \to \infty} \, n \cos \left( \frac{2}{n}  \right) \sin \left( \frac{2}{n}  \right) = 2 \,.
$$

**Solution.** We have
$$
\cos \left( \frac{2}{n}  \right) \longrightarrow 1 \,,
$$
by Theorem \ref{theorem-important-limit-1} applied with $a_n = 2/n$. Moreover
$$
\frac{\sin \left( \dfrac{2}{n}  \right)}{\dfrac{2}{n}} \longrightarrow 1 \,,
$$
by Theorem \ref{theorem-important-limit-2} applied with $a_n = 2/n$. Therefore
\begin{align*}
n \cos \left( \frac{2}{n}  \right) \sin \left( \frac{2}{n}  \right) & = 
2 \cdot \cos \left( \frac{2}{n}  \right) \cdot \frac{\sin \left( \dfrac{2}{n}  \right)}{\dfrac{2}{n}} \\
& \longrightarrow 2 \cdot 1 \cdot 1 = 2 \,,
\end{align*}
where we used the Algebra of Limits.

:::


::: Example

**Question.** Prove that
$$
\lim_{n \to \infty} \, \frac{n^2+1}{n+1} \sin \left(  \dfrac{1}{n} \right)  = 1 \,.
$$

**Solution.** Note that
\begin{align*}
\frac{n^2+1}{n+1} \sin \left(  \dfrac{1}{n} \right) & = \left( \frac{1+\dfrac{1}{n^2}}{1+ \dfrac{1}{n}} \right) \cdot \left( n \sin \left(  \dfrac{1}{n} \right) \right) \\
& \longrightarrow \frac{1 + 0}{1 + 0} \cdot 1 = 1\,,
\end{align*}
where we used (@eq-notable-limits-2) and the Algebra of Limits.


:::






